### PR TITLE
Preserve fields when welding parts in ContentElement

### LINKED ISSUE #18757: Inconsistent Weld behavior
### Describe the bug

Suppose I want to weld a `ContentPart` to a `ContentItem`, and then weld some fields to that part. It works if I do it in that order, but not the other way around.

### Orchard Core version

latest git main

### To Reproduce

Add the following example code:

```csharp
var product = new ContentItem { ContentType = "Product" };
var productPart = new ContentPart();
productPart.Weld("First", new TextField { Text = "Hello" });
productPart.Weld("Second", new TextField { Text = "World" });
product.Weld("ProductPart", productPart);
var json = (product.Content as JsonDynamicObject)?.Node.ToJsonString();
```

Observe, that `json` is `{ "ContentPart": {} }`, the fields are lost. This would be logical and expected, if `Weld()` returned a new instance, but for altering the existing content part it doesn't really make sense.

If instead, you weld the part first, it works as expected. See screenshots below.

### Expected behavior

Child elements should be inherited when welding an entity.

### Logs and screenshots

Image
Image

### PR DESCRIPTION
**Pull request by gvkries**
Updated Weld to only set Data if null or empty, preserving existing fields when welding elements. Added tests to verify fields are retained regardless of weld order. Improves reliability of part and field composition.

Fixes #18757

### CODE REVIEW

File: src/OrchardCore/OrchardCore.ContentManagement.Abstractions/ContentExtensions.cs [hunk 1]
```diff
@@ -138,7 +138,13 @@ public static ContentElement Weld(this ContentElement contentElement, string nam
     {
         if (!contentElement.Data.ContainsKey(name))
         {
-            element.Data = JObject.FromObject(element);
+            // If the element already has Data (e.g., it has been populated with fields),
+            // use it directly instead of creating a new JsonObject from the element object
+            if (element.Data is null || element.Data.Count == 0)
```
Comment (hishamco) [inline src/OrchardCore/OrchardCore.ContentManagement.Abstractions/ContentExtensions.cs:143]:
```suggestion
            if (element.Data is null or { Count: 0 )
```

**Comment by hishamco** [comment]
@sarahelsaig could please review

File: test/OrchardCore.Tests/Data/ContentItemExtensions.cs [hunk 2]
```diff
@@ -42,6 +42,65 @@ public void GetReflectsChangesToFieldMadeByApply()
         Assert.Equal(actual.Field?.Text, value);
     }
 
+    [Fact]
```
Comment (hishamco) [inline test/OrchardCore.Tests/Data/ContentItemExtensions.cs:45]: DRY, can we use theory instead

Comment (gvkries) [reply test/OrchardCore.Tests/Data/ContentItemExtensions.cs:45]: Na, that's not a good choice here. These tests differ in execution order of the weld instructions.

Comment (hishamco) [reply test/OrchardCore.Tests/Data/ContentItemExtensions.cs:45]: Ok, then let us wait for @sarahelsaig to confirm
