### PR TITLE
Use IViewEngine instead of IRazorViewEngine in RazorShapeTemplateViewEngine

### LINKED ISSUE #4570: Registration and password reset email fails with NullReferenceException if Mini Profiler is enabled
Trying to reset password with email fails with a NullReferenceException if MiniProfiler is enabled.
Tested with password reset and registration email confirm email, both fail. I guess other email sending activities may fail.

Reproduction steps:
 - Created a new webapp, added OrchardCore.Application.Cms.Targets as the guide says
 - Did basic config, enabled Email password reset. SMTP configured to use Pickup directory. Test email does appear in the pickup directory
 - Created one extra user
 - Enabled Mini Profiler
 - Go to https://localhost:5001/ForgotPassword try to reset password with either admin or the other user. Both fail with NRE
 - Disable Mini Profiler -> email "sent" (appeared in pickup directory)

I think found the cause:

image

MiniProfiler's [`ProfilingViewEngine` is `IViewEngine`](https://github.com/MiniProfiler/dotnet/blob/6b3a42a65fed15b8f8b35804668fbc2ea429402b/src/MiniProfiler.AspNetCore.Mvc/Internal/ProfilingViewEngine.cs#L11) but [RenderRazorViewAsync](https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore/OrchardCore.DisplayManagement/Razor/RazorShapeTemplateViewEngine.cs#L86) wants an `IRazorViewEngine`. So from that line 
``` csharp
var viewEngine = viewEngines[0] as IRazorViewEngine;
```
`viewEngine` is null, and fails with NRE a bit later.

Stacktrace: 

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at OrchardCore.DisplayManagement.Razor.RazorShapeTemplateViewEngine.FindView(ActionContext actionContext, String viewName, IRazorViewEngine viewEngine) in C:\projects\orchardcore\src\OrchardCore\OrchardCore.DisplayManagement\Razor\RazorShapeTemplateViewEngine.cs:line 127
   at OrchardCore.DisplayManagement.Razor.RazorShapeTemplateViewEngine.RenderViewToStringAsync(String viewName, Object model, IRazorViewEngine viewEngine) in C:\projects\orchardcore\src\OrchardCore\OrchardCore.DisplayManagement\Razor\RazorShapeTemplateViewEngine.cs:line 96
   at OrchardCore.DisplayManagement.Razor.RazorShapeTemplateViewEngine.RenderRazorViewAsync(String viewName, DisplayContext displayContext) in C:\projects\orchardcore\src\OrchardCore\OrchardCore.DisplayManagement\Razor\RazorShapeTemplateViewEngine.cs:line 88
   at OrchardCore.DisplayManagement.Implementation.DefaultHtmlDisplay.<ProcessAsync>g__Awaited|10_0(Task`1 task) in C:\projects\orchardcore\src\OrchardCore\OrchardCore.DisplayManagement\Implementation\DefaultHtmlDisplay.cs:line 264
   at OrchardCore.DisplayManagement.Implementation.DefaultHtmlDisplay.ExecuteAsync(DisplayContext context) in C:\projects\orchardcore\src\OrchardCore\OrchardCore.DisplayManagement\Implementation\DefaultHtmlDisplay.cs:line 119
   at OrchardCore.DisplayManagement.Implementation.DefaultHtmlDisplay.ExecuteAsync(DisplayContext context) in C:\projects\orchardcore\src\OrchardCore\OrchardCore.DisplayManagement\Implementation\DefaultHtmlDisplay.cs:line 173
   at OrchardCore.Users.Controllers.BaseEmailController.SendEmailAsync(String email, String subject, IShape model) in C:\projects\orchardcore\src\OrchardCore.Modules\OrchardCore.Users\Controllers\BaseEmailController.cs:line 31
   at OrchardCore.Users.Controllers.ResetPasswordController.ForgotPassword(ForgotPasswordViewModel model) in C:\projects\orchardcore\src\OrchardCore.Modules\OrchardCore.Users\Controllers\ResetPasswordController.cs:line 92
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at StackExchange.Profiling.MiniProfilerMiddleware.Invoke(HttpContext context) in C:\projects\dotnet\src\MiniProfiler.AspNetCore\MiniProfilerMiddleware.cs:line 107
   at OrchardCore.Diagnostics.DiagnosticsStartupFilter.<>c__DisplayClass3_0.<<Configure>b__1>d.MoveNext() in C:\projects\orchardcore\src\OrchardCore.Modules\OrchardCore.Diagnostics\DiagnosticsStartupFilter.cs:line 36
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute) in C:\projects\orchardcore\src\OrchardCore\OrchardCore.Abstractions\Shell\Scope\ShellScope.cs:line 152
   at OrchardCore.Modules.ModularTenantContainerMiddleware.Invoke(HttpContext httpContext) in C:\projects\orchardcore\src\OrchardCore\OrchardCore\Modules\ModularTenantContainerMiddleware.cs:line 59
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

### PR DESCRIPTION
**Pull request by AkosLukacs**
Fixes #4570 

Looks like nothing special from `IRazorViewEngine` was used, with this change emails are sent when MiniProfiler is active.

### CODE REVIEW

File: src/OrchardCore/OrchardCore.DisplayManagement/Razor/RazorShapeTemplateViewEngine.cs [hunk 1]
```diff
@@ -83,14 +83,14 @@ private async Task<IHtmlContent> RenderRazorViewAsync(string viewName, DisplayCo
...
-            var viewEngine = viewEngines[0] as IRazorViewEngine;
+            var viewEngine = viewEngines[0];
 
             var result = await RenderViewToStringAsync(viewName, displayContext.Value, viewEngine);
 
             return new HtmlString(result);
         }
 
-        public async Task<string> RenderViewToStringAsync(string viewName, object model, IRazorViewEngine viewEngine)
+        public async Task<string> RenderViewToStringAsync(string viewName, object model, IViewEngine viewEngine)
```
Comment (hishamco) [inline src/OrchardCore/OrchardCore.DisplayManagement/Razor/RazorShapeTemplateViewEngine.cs]: If it's `RazorShapeTemplateViewEngine` I see `IRazorViewEngine` is appropriate choice otherwise I can expect any other view engine. Correct me if I'm wrong?

Comment (AkosLukacs) [reply src/OrchardCore/OrchardCore.DisplayManagement/Razor/RazorShapeTemplateViewEngine.cs]: (bear with me, I'm new to Orchard so could be wrong)
Yes, and no :)
Looks like `RazorShapeTemplateViewEngine` has one Razor specific bit of code: the file name extension. It doesn't use anything specific from `IRazorViewEngine`, could work with any ViewEngine. Everything still works after changing the more generic `IViewEngine` interface.
Looked at OrchardCore's codebase, and didn't see any other view engine. IIRC view engines were introduced when Razor was a new thing, so you could use aspx and razor views. Or your own view engine, but I don't know of alternate view engines that really still exist in 2019. Might be wrong, could be on the roadmap...

In it's current state - due to line 86 - if the 0th viewEngine is not an IRazorViewEngine, `viewEngine` variable will be null. And ultimately `FindView` will fail with a NullReferenceException.
For example if you have MiniProfiler activated. It's [ProfilingViewEngine](https://github.com/MiniProfiler/dotnet/blob/6b3a42a65fed15b8f8b35804668fbc2ea429402b/src/MiniProfiler.AspNetCore.Mvc/Internal/ProfilingViewEngine.cs#L11) is an IViewEngine, doesn't know about `IRazorViewEngine`, yet profiles Razor rendering, if your view engine renders Razor.

This code change is just what seemed like the most straight-forward solution to the NullReferenceException.

**Comment by jtkech** [comment]
Yes, the `ProfilingViewEngine` wrap the original view engine.
