### PR TITLE
fix: title empty if AddSegment is not called

### LINKED ISSUE #14284: PageTitleBuilder: empty value, GenerateTitle doesn't work as expected
### Describe the bug

ORCHARD CORE VERSION 1.6.0 

in the `PageTitleBuilder` class the function `GenerateTitle` doesn't work as expected because the property **_title**, if you have one title part, have an "empty" value (see the image). 

PageTitleBuilder_bug

the "empty" type is an 'HtmlContentBuilder'. 

This check:

https://github.com/OrchardCMS/OrchardCore/blob/1fac3e7632b32ece9e22bfbaed53eac91fa32e94/src/OrchardCore/OrchardCore.DisplayManagement/Title/PageTitleBuilder.cs#L51-L54 

return true and if you have title parts set in your `PageTitleBuilder`, you can never see this values. The behavior is fixed when you call `AddSegment` function that reset the **_title** property.

The `PageTitleBuilder` code is almost the same in 1.7.0 ... but I don't know if is introduced something to avoid this issue.

### Expected behavior
The ugly solution could be replace the chek with this one: 

```
            if (_title != null && System.String.Empty != _title.GetString())
            {
                return _title;
            }
```

Where `GetString` is defined in this way: 

```
    public static class IHtmlContentExtensions
    { 
        public static string GetString(this IHtmlContent content)
        {
            using var writer = new System.IO.StringWriter();
            content.WriteTo(writer, HtmlEncoder.Default);
            return writer.ToString();
        }
    }
```

replace the `Clear` method with this one to maintain the same behavior:

```
        public void Clear()
        {
            _fixedTitle = null;
            _title = null;
            _titleParts.Clear();
        }
```

I can't understand where the "empty" value come out or the ratio behind this. This fix should not introduce a bug because there is this check:

https://github.com/OrchardCMS/OrchardCore/blob/1fac3e7632b32ece9e22bfbaed53eac91fa32e94/src/OrchardCore/OrchardCore.DisplayManagement/Title/PageTitleBuilder.cs#L62-L65 

that avoid NullReferenceException, but I don't know if this behavior is something desired.

### PR DESCRIPTION
**Pull request by PiemP**
Fixes #14284

### CODE REVIEW

File: src/OrchardCore/OrchardCore.DisplayManagement/Extensions/IHtmlContentExtensions.cs [hunk 1]
```diff
@@ -0,0 +1,15 @@
+using System.Text.Encodings.Web;
+using Microsoft.AspNetCore.Html;
+
+
+namespace OrchardCore.DisplayManagement.Extensions;
+
+public static class IHtmlContentExtensions
```
Comment (hishamco) [inline src/OrchardCore/OrchardCore.DisplayManagement/Extensions/IHtmlContentExtensions.cs:7]:
```suggestion
public static class HtmlContentExtensions
```

File: src/OrchardCore/OrchardCore.DisplayManagement/Extensions/IHtmlContentExtensions.cs [hunk 2]
```diff
@@ -0,0 +1,15 @@
+using System.Text.Encodings.Web;
+using Microsoft.AspNetCore.Html;
+
```
Comment (hishamco) [inline src/OrchardCore/OrchardCore.DisplayManagement/Extensions/IHtmlContentExtensions.cs:3]:
```suggestion
```

File: src/OrchardCore/OrchardCore.DisplayManagement/Extensions/IHtmlContentExtensions.cs [hunk 3]
```diff
@@ -0,0 +1,15 @@
...
+namespace OrchardCore.DisplayManagement.Extensions;
+
+public static class IHtmlContentExtensions
+{
+  public static string GetString(this IHtmlContent content)
+  {
+    using var writer = new System.IO.StringWriter();
+    content.WriteTo(writer, HtmlEncoder.Default);
+    return writer.ToString();
```
Comment (hishamco) [inline src/OrchardCore/OrchardCore.DisplayManagement/Extensions/IHtmlContentExtensions.cs:13]:
```suggestion

    return writer.ToString();
```

File: src/OrchardCore/OrchardCore.DisplayManagement/Extensions/IHtmlContentExtensions.cs [hunk 4]
```diff
@@ -0,0 +1,15 @@
...
+using Microsoft.AspNetCore.Html;
+
+
+namespace OrchardCore.DisplayManagement.Extensions;
+
+public static class IHtmlContentExtensions
+{
+  public static string GetString(this IHtmlContent content)
+  {
+    using var writer = new System.IO.StringWriter();
```
Comment (hishamco) [inline src/OrchardCore/OrchardCore.DisplayManagement/Extensions/IHtmlContentExtensions.cs:11]:
```suggestion
    using var writer = new StringWriter();
```

File: src/OrchardCore/OrchardCore.DisplayManagement/Extensions/IHtmlContentExtensions.cs [hunk 5]
```diff
@@ -0,0 +1,15 @@
+using System.Text.Encodings.Web;
```
Comment (hishamco) [inline src/OrchardCore/OrchardCore.DisplayManagement/Extensions/IHtmlContentExtensions.cs:1]:
```suggestion
using System.IO;
using System.Text.Encodings.Web;
```

File: src/OrchardCore/OrchardCore.DisplayManagement/Title/PageTitleBuilder.cs [hunk 6]
```diff
@@ -48,7 +49,7 @@ public IHtmlContent GenerateTitle(IHtmlContent separator)
                 return _fixedTitle;
             }
 
-            if (_title != null)
+            if (_title != null && System.String.Empty != _title.GetString())
```
Comment (hishamco) [inline src/OrchardCore/OrchardCore.DisplayManagement/Title/PageTitleBuilder.cs:52]:
```suggestion
            if (_title != null && String.Empty != _title.GetString())
```

Comment (hishamco) [reply src/OrchardCore/OrchardCore.DisplayManagement/Title/PageTitleBuilder.cs:52]: Add `using System;` above

**Review by hishamco — CHANGES_REQUESTED** [review]

File: src/OrchardCore/OrchardCore.DisplayManagement/Extensions/IHtmlContentExtensions.cs (hunk 1 above)
Comment (PiemP) [reply src/OrchardCore/OrchardCore.DisplayManagement/Extensions/IHtmlContentExtensions.cs]: Changed the name of the class and the name of the file.

File: src/OrchardCore/OrchardCore.DisplayManagement/Extensions/IHtmlContentExtensions.cs (hunk 3 above)
Comment (PiemP) [reply src/OrchardCore/OrchardCore.DisplayManagement/Extensions/IHtmlContentExtensions.cs]: added line as separator

File: src/OrchardCore/OrchardCore.DisplayManagement/Title/PageTitleBuilder.cs [hunk 7]
```diff
@@ -1,6 +1,8 @@
 using System.Collections.Generic;
 using Microsoft.AspNetCore.Html;
 using OrchardCore.DisplayManagement.Zones;
+using OrchardCore.DisplayManagement.Extensions;
+using System;
```
Comment (hishamco) [inline src/OrchardCore/OrchardCore.DisplayManagement/Title/PageTitleBuilder.cs:5]: Sort usings

**Review by hishamco — CHANGES_REQUESTED** [review]

File: src/OrchardCore/OrchardCore.DisplayManagement/Extensions/HtmlContentExtensions.cs [hunk 8]
```diff
@@ -0,0 +1,17 @@
+using System.IO;
+using System.Text.Encodings.Web;
+using Microsoft.AspNetCore.Html;
+
```
[the remark this answers is not in the document]
Comment (PiemP) [reply src/OrchardCore/OrchardCore.DisplayManagement/Extensions/HtmlContentExtensions.cs:4]: removed the extra empty line at line number 5

**Review by hishamco — APPROVED** [review]

**Comment by hishamco** [comment]
Can you add a unit tests for this?

**Comment by PiemP** [comment]
> Can you add a unit tests for this?

I try....pls be patient with me :D

File: test/OrchardCore.Tests/DisplayManagement/Title/PageTitleBuilderTests.cs [hunk 9]
```diff
@@ -0,0 +1,134 @@
...
+        }
+
+        [Fact]
+        public void FixedTitleClearAndCheck()
+        {
+            var pageTitleBuilder = _serviceProvider.GetService<IPageTitleBuilder>();
+            pageTitleBuilder.SetFixedTitle(new HtmlString("I'm a title"));
+            pageTitleBuilder.Clear();
+
+            Assert.Equal("", pageTitleBuilder.GenerateTitle().GetString());
```
Comment (hishamco) [inline test/OrchardCore.Tests/DisplayManagement/Title/PageTitleBuilderTests.cs:49]:
```suggestion
            Assert.Equal(String.Empty, pageTitleBuilder.GenerateTitle().GetString());
```

File: test/OrchardCore.Tests/DisplayManagement/Title/PageTitleBuilderTests.cs [hunk 10]
```diff
@@ -0,0 +1,134 @@
...
+            _serviceProvider = serviceCollection.BuildServiceProvider();
+        }
+
+        [Fact]
+        public void GenerateTitleEmpty()
+        {
+            var pageTitleBuilder = _serviceProvider.GetService<IPageTitleBuilder>();
+
+            
+            Assert.Equal("", pageTitleBuilder.GenerateTitle().GetString());
```
Comment (hishamco) [inline test/OrchardCore.Tests/DisplayManagement/Title/PageTitleBuilderTests.cs:30]:
```suggestion
            Assert.Equal(String.Empty, pageTitleBuilder.GenerateTitle().GetString());
```

File: test/OrchardCore.Tests/DisplayManagement/Title/PageTitleBuilderTests.cs [hunk 11]
```diff
@@ -0,0 +1,134 @@
...
+            serviceCollection.AddScoped<IPageTitleBuilder, PageTitleBuilder>();
+
+            _serviceProvider = serviceCollection.BuildServiceProvider();
+        }
+
+        [Fact]
+        public void GenerateTitleEmpty()
+        {
+            var pageTitleBuilder = _serviceProvider.GetService<IPageTitleBuilder>();
+
```
Comment (hishamco) [inline test/OrchardCore.Tests/DisplayManagement/Title/PageTitleBuilderTests.cs:28]:
```suggestion
```

**Comment by hishamco** [comment]
Thanks again @PiemP

**Comment by hishamco** [comment]
There's no fail in the build now

**Comment by Skrypt** [comment]
Make sure to not break the use case where someone wants to reset the page title by intentionally passing a string empty to RenderTitleSegments.

**Comment by PiemP** [comment]
> Make sure to not break the use case where someone wants to reset the page title by intentionally passing a string empty to RenderTitleSegments.

If someone call `RenderTitleSettings` with empty string it add a part to the title and reset the `_title` value to null. This cause the execution of the code that recreate the title. But this add a separator to the end of the title (and is the same behavior that we have now)...probably could be useful to introduce a function that render title without parameter

**Comment by PiemP** [comment]
> Make sure to not break the use case where someone wants to reset the page title by intentionally passing a string empty to RenderTitleSegments.

What did you intend with reset the page title? I have look at `RazorPage.cs` and `Page.cs` in the first case passing the empty string cause the print of the `_title` property of the `PageTitleBuilder`, in the second case this cause the reset of the `_title` to null and the regeneration of the title from the `_titleParts` (but in this case we add a separator to the end of the string).

**Comment by jtkech** [comment]
See https://github.com/OrchardCMS/OrchardCore/issues/14284#issuecomment-1714636348

File: src/OrchardCore/OrchardCore.DisplayManagement/Title/PageTitleBuilder.cs [hunk 12]
```diff
@@ -48,7 +50,7 @@ public IHtmlContent GenerateTitle(IHtmlContent separator)
                 return _fixedTitle;
             }
 
-            if (_title != null)
+            if (_title != null && String.Empty != _title.GetString())
```
Comment (MikeAlhayek) [inline src/OrchardCore/OrchardCore.DisplayManagement/Title/PageTitleBuilder.cs:53]: please use `string.Empty` instead of `String.Empty`

File: src/OrchardCore/OrchardCore.DisplayManagement/Extensions/HtmlContentExtensions.cs [hunk 13]
```diff
@@ -0,0 +1,16 @@
...
+public static class HtmlContentExtensions
+{
+  public static string GetString(this IHtmlContent content)
+  {
+    using var writer = new StringWriter();
+    content.WriteTo(writer, HtmlEncoder.Default);
+
+    return writer.ToString();
+  }
+}
```
Comment (MikeAlhayek) [inline src/OrchardCore/OrchardCore.DisplayManagement/Extensions/HtmlContentExtensions.cs:16]: Add new line at the end of this file

File: test/OrchardCore.Tests/DisplayManagement/Title/PageTitleBuilderTests.cs [hunk 14]
```diff
@@ -0,0 +1,128 @@
+using OrchardCore.DisplayManagement.Extensions;
+
+namespace OrchardCore.DisplayManagement.Title
+{
+    public class PageTitleBuilderTests
+    {
+        private const string SEPARATOR = " - ";
```
Comment (MikeAlhayek) [inline test/OrchardCore.Tests/DisplayManagement/Title/PageTitleBuilderTests.cs:7]: `Seperator`

File: test/OrchardCore.Tests/DisplayManagement/Title/PageTitleBuilderTests.cs [hunk 15]
```diff
@@ -0,0 +1,128 @@
...
+            var pageTitleBuilder = _serviceProvider.GetService<IPageTitleBuilder>();
+            
+            Assert.Equal(String.Empty, pageTitleBuilder.GenerateTitle().GetString());
+        }
+
+        [Fact]
+        public void FixedTitleSet()
+        {
+            var pageTitleBuilder = _serviceProvider.GetService<IPageTitleBuilder>();
+            pageTitleBuilder.SetFixedTitle(new HtmlString("I'm a title"));
```
Comment (MikeAlhayek) [inline test/OrchardCore.Tests/DisplayManagement/Title/PageTitleBuilderTests.cs:32]: Maybe defined all these reusable `new HtmlString("I'm a title")` into a private const

File: src/OrchardCore/OrchardCore.DisplayManagement/Title/PageTitleBuilder.cs (hunk 12 above)
Comment (PiemP) [reply src/OrchardCore/OrchardCore.DisplayManagement/Title/PageTitleBuilder.cs:53]: If I made this change VS code give me an IDE0049. Can I proceed?

Comment (MikeAlhayek) [reply src/OrchardCore/OrchardCore.DisplayManagement/Title/PageTitleBuilder.cs:53]: Yes. If you rebase your branch, you'll notice the suggestion will go away. It's something we changed in the project after you created your branch

**Comment by PiemP** [comment]
converted to draft see https://github.com/OrchardCMS/OrchardCore/issues/14284#issuecomment-1717043226

**Comment by jtkech** [comment]
@PiemP So based on our discussion, see https://github.com/OrchardCMS/OrchardCore/issues/14284#issuecomment-1718445223, here my suggestion.


        private HtmlContentBuilder _title;
        ...
        ...

        public IHtmlContent GenerateTitle(IHtmlContent separator)
        {
            ...
            ...

            if (_title is { Count: > 0 })
            {
                return _title;
            }

            ...
            ...

**Comment by PiemP** [comment]
Have I to remove 'HtmlContentExtensions' or exist some interest around it?

**Comment by jtkech** [comment]
Yes for now you can remove the extension and only use the mentioned changes.

Otherwise would need to be optimized, for example by using a `ZStringWriter`.

**Comment by PiemP** [comment]
For the tests purpose I prefer to maintain it if it's possible. Why exists 2 `ZStringWriter`? (one in `OrchardCore.Abstractions.Pooling` and one in `Cysharp.Text`)

**Comment by jtkech** [comment]
Maybe would need to be named `.ToString()`.

But not sure it's good to encourage people to use it.

If you need it in the tests, why not just using a dedicated private method in the test class.

**Review by sebastienros — APPROVED** [review]

File: test/OrchardCore.Tests/DisplayManagement/Title/PageTitleBuilderTests.cs [hunk 16]
```diff
@@ -0,0 +1,141 @@
...
+
+            pageTitleBuilder.AddSegment(new HtmlString(SimpleTitle), "after");
+
+            Assert.Equal(SimpleTitle, ToString(pageTitleBuilder.GenerateTitle()));
+        }
+
+        [Fact]
+        public void TitleMultiAddSegment()
+        {
+            var pageTitleBuilder = _serviceProvider.GetService<IPageTitleBuilder>();
```
Comment (hishamco) [inline test/OrchardCore.Tests/DisplayManagement/Title/PageTitleBuilderTests.cs:77]:
```suggestion
            // Arrange
            var pageTitleBuilder = _serviceProvider.GetService<IPageTitleBuilder>();
```

File: test/OrchardCore.Tests/DisplayManagement/Title/PageTitleBuilderTests.cs [hunk 17]
```diff
@@ -0,0 +1,141 @@
...
+        }
+
+
+        [Fact]
+        public void TitleAddSegment()
+        {
+            var pageTitleBuilder = _serviceProvider.GetService<IPageTitleBuilder>();
+            pageTitleBuilder.Clear();
+
+            pageTitleBuilder.AddSegment(new HtmlString(SimpleTitle), "after");
```
Comment (hishamco) [inline test/OrchardCore.Tests/DisplayManagement/Title/PageTitleBuilderTests.cs:69]:
```suggestion
            // Act & Assert
            pageTitleBuilder.AddSegment(new HtmlString(SimpleTitle), "after");
```

File: test/OrchardCore.Tests/DisplayManagement/Title/PageTitleBuilderTests.cs [hunk 18]
```diff
@@ -0,0 +1,141 @@
...
+            pageTitleBuilder.AddSegment(new HtmlString("you don't see me"));
+
+            Assert.Equal(SimpleTitle, ToString(pageTitleBuilder.GenerateTitle()));
+        }
+
+
+        [Fact]
+        public void TitleAddSegment()
+        {
+            var pageTitleBuilder = _serviceProvider.GetService<IPageTitleBuilder>();
```
Comment (hishamco) [inline test/OrchardCore.Tests/DisplayManagement/Title/PageTitleBuilderTests.cs:66]:
```suggestion
           // Arrange
            var pageTitleBuilder = _serviceProvider.GetService<IPageTitleBuilder>();
```

File: test/OrchardCore.Tests/DisplayManagement/Title/PageTitleBuilderTests.cs [hunk 19]
```diff
@@ -0,0 +1,141 @@
...
+            pageTitleBuilder.SetFixedTitle(new HtmlString(SimpleTitle));
+            pageTitleBuilder.Clear();
+
+            Assert.Equal(string.Empty, ToString(pageTitleBuilder.GenerateTitle()));
+        }
+
+        [Fact]
+        public void FixedTitleAddSegment()
+        {
+            var pageTitleBuilder = _serviceProvider.GetService<IPageTitleBuilder>();
```
Comment (hishamco) [inline test/OrchardCore.Tests/DisplayManagement/Title/PageTitleBuilderTests.cs:54]:
```suggestion
            // Arrange
            var pageTitleBuilder = _serviceProvider.GetService<IPageTitleBuilder>();
```

File: test/OrchardCore.Tests/DisplayManagement/Title/PageTitleBuilderTests.cs [hunk 20]
```diff
@@ -0,0 +1,141 @@
...
+            pageTitleBuilder.SetFixedTitle(new HtmlString(SimpleTitle));
+
+            pageTitleBuilder.AddSegment(new HtmlString("you don't see me"));
```
Comment (hishamco) [inline test/OrchardCore.Tests/DisplayManagement/Title/PageTitleBuilderTests.cs:57]:
```suggestion
            // Act & Assert
            pageTitleBuilder.AddSegment(new HtmlString("you don't see me"));
```

File: test/OrchardCore.Tests/DisplayManagement/Title/PageTitleBuilderTests.cs [hunk 21]
```diff
@@ -0,0 +1,141 @@
...
+        }
+
+        [Fact]
+        public void FixedTitleClearAndCheck()
+        {
+            var pageTitleBuilder = _serviceProvider.GetService<IPageTitleBuilder>();
+            pageTitleBuilder.SetFixedTitle(new HtmlString(SimpleTitle));
+            pageTitleBuilder.Clear();
+
+            Assert.Equal(string.Empty, ToString(pageTitleBuilder.GenerateTitle()));
```
Comment (hishamco) [inline test/OrchardCore.Tests/DisplayManagement/Title/PageTitleBuilderTests.cs:48]:
```suggestion
            // Act & Assert
            Assert.Equal(string.Empty, ToString(pageTitleBuilder.GenerateTitle()));
```

File: test/OrchardCore.Tests/DisplayManagement/Title/PageTitleBuilderTests.cs [hunk 22]
```diff
@@ -0,0 +1,141 @@
...
+            var pageTitleBuilder = _serviceProvider.GetService<IPageTitleBuilder>();
+            pageTitleBuilder.SetFixedTitle(new HtmlString(SimpleTitle));
+
+            Assert.Equal(SimpleTitle, ToString(pageTitleBuilder.GenerateTitle()));
+        }
+
+        [Fact]
+        public void FixedTitleClearAndCheck()
+        {
+            var pageTitleBuilder = _serviceProvider.GetService<IPageTitleBuilder>();
```
Comment (hishamco) [inline test/OrchardCore.Tests/DisplayManagement/Title/PageTitleBuilderTests.cs:44]:
```suggestion
            // Arrange
            var pageTitleBuilder = _serviceProvider.GetService<IPageTitleBuilder>();
```

File: test/OrchardCore.Tests/DisplayManagement/Title/PageTitleBuilderTests.cs [hunk 23]
```diff
@@ -0,0 +1,141 @@
...
+            Assert.Equal(string.Empty, ToString(pageTitleBuilder.GenerateTitle()));
+        }
+
+        [Fact]
+        public void FixedTitleSet()
+        {
+            var pageTitleBuilder = _serviceProvider.GetService<IPageTitleBuilder>();
+            pageTitleBuilder.SetFixedTitle(new HtmlString(SimpleTitle));
+
+            Assert.Equal(SimpleTitle, ToString(pageTitleBuilder.GenerateTitle()));
```
Comment (hishamco) [inline test/OrchardCore.Tests/DisplayManagement/Title/PageTitleBuilderTests.cs:38]:
```suggestion
            // Act & Assert
            Assert.Equal(SimpleTitle, ToString(pageTitleBuilder.GenerateTitle()));
```

File: test/OrchardCore.Tests/DisplayManagement/Title/PageTitleBuilderTests.cs [hunk 24]
```diff
@@ -0,0 +1,141 @@
...
+        {
+            var pageTitleBuilder = _serviceProvider.GetService<IPageTitleBuilder>();
+
+            Assert.Equal(string.Empty, ToString(pageTitleBuilder.GenerateTitle()));
+        }
+
+        [Fact]
+        public void FixedTitleSet()
+        {
+            var pageTitleBuilder = _serviceProvider.GetService<IPageTitleBuilder>();
```
Comment (hishamco) [inline test/OrchardCore.Tests/DisplayManagement/Title/PageTitleBuilderTests.cs:35]:
```suggestion
           // Arrange
            var pageTitleBuilder = _serviceProvider.GetService<IPageTitleBuilder>();
```

**Review by hishamco — CHANGES_REQUESTED** [review]

File: test/OrchardCore.Tests/DisplayManagement/Title/PageTitleBuilderTests.cs [hunk 25]
```diff
@@ -0,0 +1,141 @@
...
+
+            serviceCollection.AddScoped<IPageTitleBuilder, PageTitleBuilder>();
+
+            _serviceProvider = serviceCollection.BuildServiceProvider();
+        }
+
+        [Fact]
+        public void GenerateTitleEmpty()
+        {
+            var pageTitleBuilder = _serviceProvider.GetService<IPageTitleBuilder>();
```
[the remark this answers is not in the document]
Comment (PiemP) [reply test/OrchardCore.Tests/DisplayManagement/Title/PageTitleBuilderTests.cs:27]: I try to understand the meaning of "// Arrange" ... Would you like that I change the code in hte constructor and I do something like this: 

```
private readonly IPageTitleBuilder _pageTitleBuilder;

        public PageTitleBuilderTests()
        {
           _pageTitleBuilder = new PageTitleBuilder();
        }
```

And then I have to made all the canges accrodling to this one?

**Comment by Piedone** [comment]
Is this something you'd like to revisit any time soon @PiemP? Or perhaps @hishamco you can finish the nits so we can merge this, since otherwise it's all approved?

**Comment by PiemP** [comment]
😅 ... maybe I have understand the changes requested by @hisamico ... sorry guys I'm pretty new to the things related to tests ... hope to have done all right.

**Comment by hishamco** [comment]
I might revise this one

File: test/OrchardCore.Tests/DisplayManagement/Title/PageTitleBuilderTests.cs [hunk 26]
```diff
@@ -0,0 +1,147 @@
...
+            // Arrange
+            var pageTitleBuilder = (PageTitleBuilder)_serviceProvider.GetService<IPageTitleBuilder>();
+            pageTitleBuilder.Clear();
+
+            var elements = new IHtmlContent[]
+            {
+                new HtmlString(FirstPartTitle),
+                new HtmlString(SecondPartTitle)
+            };
+            pageTitleBuilder.AddSegments(elements, "after");
```
Comment (hishamco) [inline test/OrchardCore.Tests/DisplayManagement/Title/PageTitleBuilderTests.cs:134]:
```suggestion

            pageTitleBuilder.AddSegments(elements, "after");
```

File: test/OrchardCore.Tests/DisplayManagement/Title/PageTitleBuilderTests.cs [hunk 27]
```diff
@@ -0,0 +1,147 @@
...
+
+            // Act & Assert
+            Assert.Equal($"{FirstPartTitle}{Separator}{SecondPartTitle}", ToString(pageTitleBuilder.GenerateTitle(new HtmlString(Separator))));
+        }
+        private static string ToString(IHtmlContent content)
```
Comment (hishamco) [inline test/OrchardCore.Tests/DisplayManagement/Title/PageTitleBuilderTests.cs:139]:
```suggestion

        private static string ToString(IHtmlContent content)
```

**Review by hishamco — CHANGES_REQUESTED** [review]

**Review by hishamco — APPROVED** [review]

**Comment by Piedone** [comment]
Great, thank you!
