### PR TITLE
Fixes #9018 Shape AddAsync() in place of Add().

### LINKED ISSUE #9018: Ordering of list items in Admin when managing content items
### Describe the bug

In build rc2-15500 you had the ability to reorder list items within a content item.  the cross arrows appeared and you were able to move items up and down.

I am not sure what build this happened in but if i get rc2-16037 the cross arrows for reorder no longer exist.

### To Reproduce

1. Create a Basic Orchard App in VS targeting OrchardCore.Application.Cms.Targets rc2-15500
2. Create a Blog site from the blog recipe
3. Go to the admin, Content Types and Edit the Blog content type
4. Edit the List Part and Enable Ordering
5. Add one more blog post
6. You will see the cross arrows for reordering
7. Change the Target of  OrchardCore.Application.Cms.Targets to rc2-16037
8. You no longer see the cross arrows

### Expected behavior
To see the cross arrows and be able to reorder

### PR DESCRIPTION
**Pull request by jtkech**
Fixes #9018

### CODE REVIEW

File: src/OrchardCore/OrchardCore.DisplayManagement/Zones/ZoneHoldingBehavior.cs [hunk 1]
```diff
@@ -191,7 +191,7 @@ public override bool TryConvert(System.Dynamic.ConvertBinder binder, out object
 
         public override bool Equals(object obj)
         {
-            if (ReferenceEquals(null, obj))
+            if (obj is null)
```
Comment (Skrypt) [inline src/OrchardCore/OrchardCore.DisplayManagement/Zones/ZoneHoldingBehavior.cs:194]: I knew it that ZOD had a bad behavior.
