### PR TITLE
Fix SectionDisplayDriver prefix

### LINKED ISSUE #15116: SectionDisplayDriver should override the HtmlPrefix with the TSectionName
Currently the `SectionDisplayDriver` uses `TSection` for it's `Entity` property name :
https://github.com/OrchardCMS/OrchardCore/blob/ae2f9525e29f533b1a993d7279c9a45d06ac5198/src/OrchardCore/OrchardCore.DisplayManagement/Entities/SectionDisplayDriver.cs#L28

However, it does not override the default `Prefix` value, which remains as per the base class `Prefix = typeof(TModel).Name;`

This creates ambiguity on the field names, where it is easily possible to have multiple keys of the same name, if classes used on `IEntity` have the same property names.

e.g.

```
public record PropertyA(bool Allow);
public record PropertyB(bool Allow);
```

`PropertyA` and `PropertyB` will be stored seperately in the properties dictionary correctly, but the views will create a form post with identical names.

### PR DESCRIPTION
**Pull request by MikeAlhayek**
Fix #15116

The prefix is is `{TModel}.{TSection}`

Screenshot_4

### CODE REVIEW

File: src/OrchardCore/OrchardCore.DisplayManagement/Handlers/DisplayDriver.cs [hunk 1]
```diff
@@ -115,12 +115,17 @@ public virtual Task<IDisplayResult> UpdateAsync(TModel model, IUpdateModel updat
 
         protected virtual void BuildPrefix(TModel model, string htmlFieldPrefix)
         {
-            Prefix = typeof(TModel).Name;
+            var builder = new StringBuilder();
```
Comment (deanmarcussen) [inline src/OrchardCore/OrchardCore.DisplayManagement/Handlers/DisplayDriver.cs:118]: I would have to benchmark it to be sure, but I think you're probably increasing allocations by making this change to a stringbuilder.

Comment (MikeAlhayek) [reply src/OrchardCore/OrchardCore.DisplayManagement/Handlers/DisplayDriver.cs]: @deanmarcussen yes you were right. I thought because StringBuilder use Span behind the seance, I thought it would reduce allocation. But I think in this case it's not a huge string and only a single concatenation.

I remove StringBuilder and used concatenation instead. Let me know if you see anything else or if you approve.
