### PR TITLE
Fix "The node already has a parent." exception when setting JsonNode in Workflows ForEach Task

### LINKED ISSUE #16846: "The node already has a parent." exception when setting JsonNode in Workflows ForEach Task
Title: System.InvalidOperationException: The node already has a parent. when setting JsonNode in OrchardCore Workflows

Description: I encountered a System.InvalidOperationException: The node already has a parent. when working with JsonNode in OrchardCore workflows. The error occurs when setting a JsonNode as the current value in a ForEachTask activity. It seems that the same JsonNode is being assigned to multiple parents, which causes the exception.

Error Message:

```
mathematica
复制代码
System.InvalidOperationException
  HResult=0x80131509
  Message=The node already has a parent.
  Source=System.Text.Json
  StackTrace:
   at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_NodeAlreadyHasParent()
   at System.Text.Json.Nodes.JsonObject.SetItem(String propertyName, JsonNode value)
   at OrchardCore.Workflows.Activities.Activity.SetProperty(Object value, String name) in E:\Test\test-orchard-core1\src\OrchardCore\OrchardCore.Workflows.Abstractions\Activities\Activity.cs:line 149
   at OrchardCore.Workflows.Activities.ForEachTask.set_Current(Object value) in E:\Test\test-orchard-core1\src\OrchardCore.Modules\OrchardCore.Workflows\Activities\ForEachTask.cs:line 47
   at OrchardCore.Workflows.Activities.ForEachTask.<ExecuteAsync>d__20.MoveNext() in E:\Test\test-orchard-core1\src\OrchardCore.Modules\OrchardCore.Workflows\Activities\ForEachTask.cs:line 74
```

Steps to Reproduce:

Create a workflow in OrchardCore that includes a ForEachTask activity.
Iterate over a collection of JsonNode objects.
Set a JsonNode object as the current value of the task in each iteration.
The exception is thrown because the JsonNode has already been assigned to a parent.
Expected Behavior: There should be no exception when setting a JsonNode in each iteration of the ForEachTask. Either JsonNode should be cloned or detached from its current parent before being reassigned.

Actual Behavior: An exception is thrown because JsonNode is being reused and assigned to multiple parents.

Possible Solutions:

Clone the JsonNode using DeepClone() before assigning it to avoid parent conflicts.
Remove the JsonNode from its current parent before reassigning it.

Environment:

OrchardCore version: 2.0
.NET version: .net8.0
Operating System: windows

### PR DESCRIPTION
**Pull request by zl2fxy**
"The node already has a parent." exception when setting JsonNode in Workflows ForEach Task

Fix #16846

### CODE REVIEW

File: src/OrchardCore/OrchardCore.Workflows.Abstractions/Activities/Activity.cs [hunk 1]
```diff
@@ -146,6 +146,6 @@ protected virtual T GetProperty<T>(Type type, Func<T> defaultValue = null, [Call
     protected virtual void SetProperty(object value, [CallerMemberName] string name = null)
     {
         // Properties[name] = JToken.FromObject(value);
-        Properties[name] = JNode.FromObject(value);
+        Properties[name] = JNode.FromObject(value).DeepClone();;
```
Comment (gvkries) [inline src/OrchardCore/OrchardCore.Workflows.Abstractions/Activities/Activity.cs:149]:
```suggestion
        Properties[name] = value is JsonNode node ? node.DeepClone() : JNode.FromObject(value);
```
Isn't it enough to clone the node if it already is one? Otherwise it's a freshly serialized object with no parent, isn't it?
