### PR TITLE
Preserve the `RequestUrlPrefix` of tenants when running the `ModularBackgroundService`

### LINKED ISSUE #18592: Resorce management ContentBasePath malformed
### Describe the bug

We've likely discovered a bug in resource management.

Occassionally, the [ContentBasePath](https://github.com/OrchardCMS/OrchardCore/blob/f4a3c340d1b3a035d40db6c35728042e910ec87e/src/OrchardCore.Modules/OrchardCore.Resources/ResourceManagementOptionsConfiguration.cs#L1268) inside ResourceManagement is set to '/' instead of tenant prefix or an empty string.

This results in 404 errors for all resources — scripts, links, CSS. I attempted to debug this, but since it happens only sporadically and we haven’t found any pattern yet, it’s unclear what exactly causes it.

My current hypothesis is that the [ShellScope.Context](https://github.com/OrchardCMS/OrchardCore/blob/f4a3c340d1b3a035d40db6c35728042e910ec87e/src/OrchardCore/OrchardCore/Modules/ModularTenantRouterMiddleware.cs#L26) in ModularTenantRouterMiddlewares being switched to the Default tenant after entering the [if-condition](https://github.com/OrchardCMS/OrchardCore/blob/f4a3c340d1b3a035d40db6c35728042e910ec87e/src/OrchardCore/OrchardCore/Modules/ModularTenantRouterMiddleware.cs#L31). The default tenant has empty RequestUrlPrefix which might cause the incorrect PathBase = '/'.

If this is the case, it would imply that the value inside [AsyncLocal<ShellScopeHolder>](https://github.com/OrchardCMS/OrchardCore/blob/f4a3c340d1b3a035d40db6c35728042e910ec87e/src/OrchardCore/OrchardCore.Abstractions/Shell/Scope/ShellScope.cs#L14) is being changed unexpectedly, possibly by another thread or due to some async behavior.

The bigger issue is that even though this happens only occasionally, resource management options are initialized only at startup. So once this occurs, the admin theme breaks and the entire project needs a restart.

Do you have any ideas on what else we could inspect or how we might reliably reproduce this?

Possible solution:

It seems that simply modifying the assignment in [ResourceManagementOptionsConfiguration](https://github.com/OrchardCMS/OrchardCore/blob/f4a3c340d1b3a035d40db6c35728042e910ec87e/src/OrchardCore.Modules/OrchardCore.Resources/ResourceManagementOptionsConfiguration.cs#L1268)
from
 options.ContentBasePath =  _pathBase.Value;
to 
 options.ContentBasePath = "/" + shellContext.Settings.RequestUrlPrefix;
could be a workaround.

### Orchard Core version

2.2
(it does not happen on similiar solutions on 1.8.4)

### To Reproduce

unknown - happens on solutions with multiple tenants, rest apis

### Logs and screenshots

I replaced ResourceManagementOptionsConfiguration with a custom implementation to capture this situation:

Image

After the issue occurred, the logs contain:

2025-11-27 00:51:30Z|||PuxOverride.Resources.ResourceManagementOptionsConfiguration|ERR|Mismatch / between ResourceManagementOptionsConfiguration PathBase '/' and Shell RequestUrlPrefix ''|

RequestUrlPrefix is correct because this is the Default tenant.
However, what's strange is that the tenant name is missing from the log.
It should be something like:

2025-11-27 00:51:30Z||Default|....

### PR DESCRIPTION
**Pull request by gvkries**
Updated the `SetBaseUrl` logic to only set `PathBase` if the path is not just `/`, preserving any existing request URL prefix.

Fixes #18592

### CODE REVIEW

File: src/OrchardCore/OrchardCore/Modules/ModularBackgroundService.cs [hunk 1]
```diff
@@ -430,4 +430,25 @@ private void CleanSchedulers(string tenant, IEnumerable<IBackgroundTask> tasks)
...
+            if (!string.IsNullOrEmpty(uri.AbsolutePath) && uri.AbsolutePath != "/")
+            {
+                context.Request.PathBase = uri.AbsolutePath;
+            }
+
+            if (!string.IsNullOrWhiteSpace(uri.Query))
+            {
+                context.Request.QueryString = new QueryString(uri.Query);
+            }
+        }
```
Comment (Piedone) [inline src/OrchardCore/OrchardCore/Modules/ModularBackgroundService.cs:449]: Nothing to complain about with the actual changes, but how about an early return while we're at it?


```suggestion
    private static void SetBaseUrl(HttpContext context, string baseUrl)
    {
        if (!Uri.TryCreate(baseUrl, UriKind.Absolute, out var uri))
        {
            return;
        }

        context.Request.Scheme = uri.Scheme;
        context.Request.Host = new HostString(uri.Host, uri.Port);

        // Set the PathBase only if it's not just "/". Otherwise, the original path base is kept, which may
        // contain the RequestUrlPrefix if any.
        if (!string.IsNullOrEmpty(uri.AbsolutePath) && uri.AbsolutePath != "/")
        {
            context.Request.PathBase = uri.AbsolutePath;
        }

        if (!string.IsNullOrWhiteSpace(uri.Query))
        {
            context.Request.QueryString = new QueryString(uri.Query);
        }
    }
```
