### PR TITLE
Show an error message if permission names are not unique

### LINKED ISSUE #8469: Roles with the variable name across modules conflict with each other
When creating a new module to build my own workflows I called Acme.Modules.Workflows, I added a permission class and named a permission "ManageWorkflows". When the Roles screen enumerates the roles to be selected, the checkbox for these roles created a unique id on the page of Checkbox.ManageWorkflows for both the Orchard Workflows module and mine. We Probably need a unique id to underscore the the Module Name or namespace it is coming from. "Acme_ManageWorkflows"

The result is you can't check your permissions properly, it this could potentially trickle down to setting the wrong permissions.

### PR DESCRIPTION
**Pull request by gvkries**
Currently, permission names are expected to be unique across all modules. This change displays an error message in the Role Editor when a permission name is reused. This alerts the administrator to possible security issues when a module redefines an existing permission.

Fixes #8469

### CODE REVIEW

**Comment by gvkries** [comment]
I understand the concern about breaking existing applications, but the security implications of reusing permission names are significant:

1. **Security Risk**: Reusing permission names can lead to unauthorized access if existing roles already grant the reused permission. This creates a serious vulnerability.

2. **High Impact**: The potential consequences of such conflicts are severe. Logging a warning might not be enough, as it could be overlooked, allowing the issue to persist.

3. **Immediate Action**: Throwing an exception ensures the problem is addressed immediately, aligning with the fail-fast principle to catch and fix errors early.

While the current solution only causes the admin portal to fail, it highlights the issue and prompts immediate action. Given the high stakes, enforcing an exception is necessary to maintain application security.

**Comment by MikeAlhayek** [comment]
I understand the concert. This is something I also mentioned few weeks back in the meeting. But I don't think its a justification for throwing a runtime exception. I think logging it as a warning is enough unless we need to try to use namespace to ensure uniqueness which is also bad since it would increase the cookie size.

**Comment by gvkries** [comment]
Okay, instead of throwing an exception, I'm content to show an error in the admin portal. I think that the mere logging has too little visibility.

I also admit that the previous solution was not sufficient because throwing an exception in the `DefaultPermissionsService` and admin portal is not reliable enough. For the same reason, I think that logging there is not good enough as well and I have therefore refrained from doing so for the time being.

**Comment by gvkries** [comment]
Note: Changing the permission names to include the module name or namespace is not an easy solution. This would be a massive breaking change IMHO.

**Comment by MikeAlhayek** [comment]
> Note: Changing the permission names to include the module name or namespace is not an easy solution. This would be a massive breaking change IMHO.

Yes I agree. I am not suggesting that either. I think we should log warning and not throw an exception.

**Comment by gvkries** [comment]
@MikeAlhayek Maybe we can briefly talk about this tomorrow.

**Comment by MikeAlhayek** [comment]
Absolutely

**Review by sebastienros — APPROVED** [review]

**Review by sebastienros — COMMENTED** [review]
Add some log on startup.

**Comment by gvkries** [comment]
@MikeAlhayek I added a log message during startup and some basic documentation. Let me know if that is helpful.

File: src/OrchardCore/OrchardCore.Infrastructure/Security/OrchardCoreBuilderExtensions.cs [hunk 1]
```diff
@@ -30,6 +33,31 @@ public static OrchardCoreBuilder AddSecurity(this OrchardCoreBuilder builder)
...
 
+        builder.Configure(ValidatePermissionsAsync);
+
         return builder;
     }
+
+    private static async ValueTask ValidatePermissionsAsync(IApplicationBuilder builder, IEndpointRouteBuilder routeBuilder, IServiceProvider serviceProvider)
+    {
+        // Make sure registered permissions are valid, i.e. they must be unique.
+        var permissionProviders = serviceProvider.GetServices<IPermissionProvider>();
```
Comment (MikeAlhayek) [inline src/OrchardCore/OrchardCore.Infrastructure/Security/OrchardCoreBuilderExtensions.cs:44]: This logic is repeated few times. I think it would be helpful to add a new method to `DefaultPermissionService` that would keep track of the duplicated permission.

This way this is something we don't need to compute more than once during the tenant lifecycle.

Comment (gvkries) [reply src/OrchardCore/OrchardCore.Infrastructure/Security/OrchardCoreBuilderExtensions.cs:44]: As the permissions are usually only required in the admin portal, I don't think it is good to cache them forever. And adding them to the memory cache is also not really required, because computing them is cheap enough.

Regarding adding this to the permission service instead, it would also mean to log this error in the service each time the permissions are enumerated. I therefore think this one duplication of similar code is a better choice.

File: src/OrchardCore.Modules/OrchardCore.Roles/Controllers/AdminController.cs [hunk 2]
```diff
@@ -167,11 +167,17 @@ public async Task<IActionResult> Edit(string id)
...
         };
 
+        var installedPermissions = await GetInstalledPermissionsAsync();
+        var allPermissions = installedPermissions.SelectMany(x => x.Value);
+
+        ViewData["DuplicatedPermissions"] = allPermissions
+            .GroupBy(p => p.Name.ToUpperInvariant())
+            .Where(g => g.Count() > 1)
+            .Select(g => g.First().Name)
+            .ToArray();
```
[the remark this answers is not in the document]
Comment (gvkries) [reply src/OrchardCore.Modules/OrchardCore.Roles/Controllers/AdminController.cs:177]: The controller is slightly different in listing the permissions as in the permission service; they are grouped by providers in one step.

File: src/OrchardCore/OrchardCore.Infrastructure/Security/OrchardCoreBuilderExtensions.cs (hunk 1 above)
Comment (MikeAlhayek) [reply src/OrchardCore/OrchardCore.Infrastructure/Security/OrchardCoreBuilderExtensions.cs:44]: We already keep track of all the permissions in that singleton class. In the LoadPermission method which is computed once, you can also check for duplication and store duplicated permissions. This way you can log more info as the full name (including namespace) of the conflicted permissions.  I don't think it would take up much memory since most of the time we won't have the duplicate issue and if we did, it won't be much. So I think it's better to cache duplication "if any", this way it's always available and we don't have to compute it more than once and it is part of a service instead of doing the same check is multiple places.

Comment (gvkries) [reply src/OrchardCore/OrchardCore.Infrastructure/Security/OrchardCoreBuilderExtensions.cs:44]: Oh, you're right. I'll think more about this...

File: src/OrchardCore.Modules/OrchardCore.Roles/Controllers/AdminController.cs (hunk 2 above)
[the remark this answers is not in the document]
Comment (MikeAlhayek) [reply src/OrchardCore.Modules/OrchardCore.Roles/Controllers/AdminController.cs:177]: Yes but if you have a list that would give you the duplicated Permissions by the service, you can chose what you want to do with that info on the UI

File: src/OrchardCore/OrchardCore.Infrastructure/Security/OrchardCoreBuilderExtensions.cs (hunk 1 above)
Comment (gvkries) [reply src/OrchardCore/OrchardCore.Infrastructure/Security/OrchardCoreBuilderExtensions.cs:44]: Actually you were wrong ;-) The `DefaultPermissionService` is registered as scoped and the permissions are not cached by it for the app lifetime. And they are not required to be cached forever as well, as they are used only in the portal and even there not all the time. So I don't think we should change that.

I also don't think it is a good idea to add the "duplicated permissions" info as a new public API surface to the `IPermissionService`. This is a internal implementation detail, that should not be exposed publicly.

I therefore propose to leave it separated as suggested.

File: src/OrchardCore.Modules/OrchardCore.Roles/Controllers/AdminController.cs (hunk 2 above)
[the remark this answers is not in the document]
Comment (gvkries) [reply src/OrchardCore.Modules/OrchardCore.Roles/Controllers/AdminController.cs:177]: See above...

File: src/OrchardCore/OrchardCore.Infrastructure/Security/OrchardCoreBuilderExtensions.cs (hunk 1 above)
Comment (MikeAlhayek) [reply src/OrchardCore/OrchardCore.Infrastructure/Security/OrchardCoreBuilderExtensions.cs:44]: Okay. I for some reason thought DefaultPermissionService was a singleton object.

**Review by MikeAlhayek — APPROVED** [review]
