### PR TITLE
DisplayAsync to return actual pre-rendered IHtmlContent 

### LINKED ISSUE #15211: .net8+orchardcore blazorserver mode render component error
### Describe the bug

.net8+orchardcore create webpage, use blazorserver mode @(await Html.RenderComponentAsync<Component>(RenderMode.ServerPrerendered)) error.

error content:
System.InvalidOperationException: The current thread is not associated with the Dispatcher. Use InvokeAsync() to switch execution to the Dispatcher when triggering rendering or component state.

### To Reproduce
1. Create a OrchardCore app, add module, and add WebPage page.
2. Create blazorclasslibrary project, add default Component.
3. call Html.RenderComponentAsync in webpage.
4. browser webpage.

### Expected behavior
System.InvalidOperationException: The current thread is not associated with the Dispatcher. Use InvokeAsync() to switch execution to the Dispatcher when triggering rendering or component state.

### Screenshots
a1
a2

### LINKED ISSUE #15235: .net8+orchardcore blazorserver mode render component error
Describe the bug
.net8+orchardcore create webpage, use blazorserver mode @(await Html.RenderComponentAsync(RenderMode.ServerPrerendered)) error.

error content:
System.InvalidOperationException: The current thread is not associated with the Dispatcher. Use InvokeAsync() to switch execution to the Dispatcher when triggering rendering or component state.

To Reproduce

Create a OrchardCore app, add module, and add WebPage page.
Create blazorclasslibrary project, add default Component.
call Html.RenderComponentAsync in webpage.
browser webpage.
Expected behavior
System.InvalidOperationException: The current thread is not associated with the Dispatcher. Use InvokeAsync() to switch execution to the Dispatcher when triggering rendering or component state.

. net7 is normal,. net8 is incorrect, the environment is .net8+orcardcore, not console

Screenshots
a1
a2

a3

### PR DESCRIPTION
**Pull request by ns8482e**
Component tag helper / Html Helper is not able to render Razor Components for nested `PositionWrapper` components in .NET8.

Suggested change here to have,  `DisplayAsync` to return actual pre-rendered `IHtmlContent`  instead of `PositionWrapper`

Fixes #15235
Fixes #15211

/cc @sebastienros

### CODE REVIEW

File: src/OrchardCore/OrchardCore.DisplayManagement/Implementation/DefaultHtmlDisplay.cs [hunk 1]
```diff
@@ -50,7 +50,19 @@ public async Task<IHtmlContent> ExecuteAsync(DisplayContext context)
...
+                if (htmlContent is PositionWrapper wrapper)
+                {
+                    while (wrapper.Value is PositionWrapper)
+                    {
+                        wrapper = (PositionWrapper)wrapper.Value;
+                    }
+
+                    return wrapper.Value;
+                }
+                else
```
Comment (MikeAlhayek) [inline src/OrchardCore/OrchardCore.DisplayManagement/Implementation/DefaultHtmlDisplay.cs:62]: you can remove the else block and just return instead

File: src/OrchardCore/OrchardCore.DisplayManagement/Implementation/DisplayHelper.cs [hunk 2]
```diff
@@ -75,7 +76,19 @@ public Task<IHtmlContent> ShapeExecuteAsync(IShape shape)
...
+                {
+                    while(wrapper.Value is PositionWrapper)
+                    {
+                        wrapper = (PositionWrapper) wrapper.Value;
+                    }
+                    
+                    return Task.FromResult(wrapper.Value);
+                }
+                else
+                {
```
Comment (MikeAlhayek) [inline src/OrchardCore/OrchardCore.DisplayManagement/Implementation/DisplayHelper.cs:89]: same here drop the use of else block and just return

File: src/OrchardCore/OrchardCore.DisplayManagement/PositionWrapper.cs [hunk 3]
```diff
@@ -41,6 +41,14 @@ public PositionWrapper(string value, string position)
             Position = position;
         }
 
+        internal IHtmlContent Value
```
Comment (MikeAlhayek) [inline src/OrchardCore/OrchardCore.DisplayManagement/PositionWrapper.cs:44]: Vlaue => _value;

File: src/OrchardCore/OrchardCore.DisplayManagement/Implementation/DefaultHtmlDisplay.cs (hunk 1 above)
Comment (ns8482e) [reply src/OrchardCore/OrchardCore.DisplayManagement/Implementation/DefaultHtmlDisplay.cs]: Removed

File: src/OrchardCore/OrchardCore.DisplayManagement/Implementation/DisplayHelper.cs (hunk 2 above)
Comment (ns8482e) [reply src/OrchardCore/OrchardCore.DisplayManagement/Implementation/DisplayHelper.cs]: Removed

File: src/OrchardCore/OrchardCore.DisplayManagement/PositionWrapper.cs (hunk 3 above)
Comment (ns8482e) [reply src/OrchardCore/OrchardCore.DisplayManagement/PositionWrapper.cs]: done

File: src/OrchardCore/OrchardCore.DisplayManagement/Implementation/DefaultHtmlDisplay.cs [hunk 4]
```diff
@@ -50,6 +50,16 @@ public async Task<IHtmlContent> ExecuteAsync(DisplayContext context)
             // Check if the shape is pre-rendered.
             if (shape is IHtmlContent htmlContent)
             {
+                if (htmlContent is PositionWrapper wrapper)
+                {
+                    while (wrapper.Value is PositionWrapper)
```
Comment (MikeAlhayek) [inline src/OrchardCore/OrchardCore.DisplayManagement/Implementation/DefaultHtmlDisplay.cs:55]: Should this be an if statement or a while loop?

Also change it to 
(wrapper.Value is PositionWrapper positionWrapper)  

So you don't have to cast again

Comment (ns8482e) [reply src/OrchardCore/OrchardCore.DisplayManagement/Implementation/DefaultHtmlDisplay.cs:55]: no need to re define new variable `positionWrapper`, wrapper is already defined in if statement, i am reusing same var

Comment (ns8482e) [reply src/OrchardCore/OrchardCore.DisplayManagement/Implementation/DefaultHtmlDisplay.cs]: I see what you are suggesting! - updated

**Review by MikeAlhayek — APPROVED** [review]

File: src/OrchardCore/OrchardCore.DisplayManagement/Implementation/DisplayHelper.cs [hunk 5]
```diff
@@ -4,6 +4,7 @@
 using System.Linq;
 using System.Threading.Tasks;
 using Microsoft.AspNetCore.Html;
+using Microsoft.CodeAnalysis.CSharp.Syntax;
```
Comment (MikeAlhayek) [inline src/OrchardCore/OrchardCore.DisplayManagement/Implementation/DisplayHelper.cs:7]: I don't think you need this

File: src/OrchardCore/OrchardCore.DisplayManagement/Implementation/DefaultHtmlDisplay.cs [hunk 6]
```diff
@@ -50,6 +50,16 @@ public async Task<IHtmlContent> ExecuteAsync(DisplayContext context)
             // Check if the shape is pre-rendered.
             if (shape is IHtmlContent htmlContent)
             {
+                if (htmlContent is PositionWrapper wrapper)
```
[the remark this answers is not in the document]
Comment (sebastienros) [reply src/OrchardCore/OrchardCore.DisplayManagement/Implementation/DefaultHtmlDisplay.cs:53]: Example of things to try with this change: Widgets, FlowPart, BagPart, GraphQL rendering, layouts, custom placement.

[the remark this answers is not in the document]
Comment (ns8482e) [reply src/OrchardCore/OrchardCore.DisplayManagement/Implementation/DefaultHtmlDisplay.cs:53]: It would not break anything in OC, rather fixes Blazor component rendering. 

This PR  returns the original pre-rendered IHtmlContent when the shape provided in DisplayAsync is PositionWrapper.

PositionWrapper is nothing but holds pre-rendered IHtmlContent, and it can only contain one IHtmlContent.  Hence there no need of nesting PositionWrapper in PositionWrapper. 

Currently In ThemeLayout we use PositionWrapper to pre-render (while maintaining position on zone) before we place on Layout. This allows to have lazy placed zones to be rendered on Layout but requires us to call DisplayAsync twice, that unnecessary nests PositionWrapper in PositionWrapper.

**Comment by sebastienros** [comment]
> there no need of nesting PositionWrapper in PositionWrapper.

I had not understood this at first look. Now I get it, I thought your code was removing all wrappers, not just the nested ones. And this is raising a good point actually, maybe we shouldn't wrap position wrappers, that is kind of a bug. Can you try to do that instead?

We could also add a `static IHtmlContent TryWrap()` in `PositionWrapper` to handle `string`, `PositionWrapper` and `IHtmlContent` (using pattern matching) so we don't duplicate the logic and it would return the correct results.

**Comment by ns8482e** [comment]
I'll update the code, to use static `TryWrap` instead of using constructor. However to avoid nested wrapper we still need to unwrap  the wrapper to return underlying `IHtmlContent` on shape execute.

**Comment by ns8482e** [comment]
> maybe we shouldn't wrap position wrappers

FYI @sebastienros , this happens when the `PositonWrapper` is within the `_items` of `ZoneShapes` and  `DisplayAsync` is called on  `Zone` / `ContentZone`.

File: src/OrchardCore/OrchardCore.DisplayManagement/PositionWrapper.cs [hunk 7]
```diff
@@ -50,5 +51,24 @@ public ValueTask<IShape> AddAsync(object item, string position)
         {
             throw new System.NotImplementedException();
         }
+
+        public static PositionWrapper TryWrap(object value, string position)
+        {
+            if (value is PositionWrapper wrapper)
```
Comment (sebastienros) [inline src/OrchardCore/OrchardCore.DisplayManagement/PositionWrapper.cs:57]: `is IPositioned`?

File: src/OrchardCore/OrchardCore.DisplayManagement/Shapes/Shape.cs [hunk 8]
```diff
@@ -65,13 +65,13 @@ public virtual ValueTask<IShape> AddAsync(object item, string position)
 
             _items ??= [];
 
-            if (item is IHtmlContent)
+            if (item is IHtmlContent htmlContent)
```
Comment (sebastienros) [inline src/OrchardCore/OrchardCore.DisplayManagement/Shapes/Shape.cs:68]: Can't this whole if/else/else be a single TryWrap?

File: src/OrchardCore/OrchardCore.DisplayManagement/PositionWrapper.cs [hunk 9]
```diff
@@ -50,5 +51,24 @@ public ValueTask<IShape> AddAsync(object item, string position)
...
+                // Update the new Position
+                wrapper.Position = position;
+                return wrapper;
+            }
+            else if (value is IHtmlContent content)
+                return new PositionWrapper(content, position);
+            else if (value is string stringContent)
+                return new PositionWrapper(stringContent, position);
+            else
+                throw new System.NotSupportedException($"Type of {nameof(value)} must be either {nameof(String)}, {nameof(IHtmlContent)} or {nameof(PositionWrapper)}.");
```
Comment (sebastienros) [inline src/OrchardCore/OrchardCore.DisplayManagement/PositionWrapper.cs:68]: `TryWrap` should it return a new wrapper in this case instead of throwing?

Comment (sebastienros) [reply src/OrchardCore/OrchardCore.DisplayManagement/PositionWrapper.cs:68]: Should it unwrap if the position is "" ? Is that the meaning of "" in ThemeLayout.cs?

Comment (ns8482e) [reply src/OrchardCore/OrchardCore.DisplayManagement/PositionWrapper.cs:68]: > `TryWrap` should it return a new wrapper in this case instead of throwing?

Throwing `NotSupportedException` because `value` is not either string, `IHtmlContent` or `PositionWrapper`.

File: src/OrchardCore/OrchardCore.DisplayManagement/PositionWrapper.cs (hunk 7 above)
Comment (ns8482e) [reply src/OrchardCore/OrchardCore.DisplayManagement/PositionWrapper.cs:57]: I used `PositionWrapper` because return value must be both `IPositioned` and `IShape`

Comment (ns8482e) [reply src/OrchardCore/OrchardCore.DisplayManagement/PositionWrapper.cs:57]: Are you suggesting to change to return `IShape`? like below?
```cs
 public static IShape TryWrap(object value, string position)
    {
        if (value is IShape && value is IPositioned wrapper )
        {
           ....
                           return wrapper as IShape;
        }
  }
```

**Comment by sebastienros** [comment]
I saw a test failing on the CI

File: src/OrchardCore/OrchardCore.DisplayManagement/Shapes/Shape.cs (hunk 8 above)
Comment (ns8482e) [reply src/OrchardCore/OrchardCore.DisplayManagement/Shapes/Shape.cs]: updated

**Comment by ns8482e** [comment]
> I saw a test failing on the CI

fixed
