### PR TITLE
Ensure that no callbacks are added to the ShellScope during termination

### LINKED ISSUE #17930: Got Collection was modified; enumeration operation may not execute. at ShellScope.BeforeDisposeAsync() when disconnecting a SignalR connection
### Describe the bug

In my production project, when starting SignalR connection by calling `await connection.start();` immediately when loading a script, I found error messages in `App_Data/logs` as following:
```txt
An unhandled exception has occurred while executing the request. System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at OrchardCore.Environment.Shell.Scope.ShellScope.BeforeDisposeAsync()....
```
(partial, full log are below)

### Orchard Core version

2.1.7

### To Reproduce

I can't reproduce this issue with a new project that has the same signalR function as my production project. 
You can clone it from this link https://github.com/aaronamm/orchard-core-issue 
and run it on your local machine.

However, here are what I found:
- When a user has logged in, there is no error.
- If `connection.start()` get called inside React component (useEffect), there is no error.

### Expected behavior

Calling `connection.start()` immediately should not output error message.

### Logs and screenshots

```txt
2025-05-18 13:08:36.1195|Default|00-7698c87ab758c47f61a3a49cb5750f29-efb5ea0bc6ac562d-00|1|Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware|ERROR|An unhandled exception has occurred while executing the request. System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at OrchardCore.Environment.Shell.Scope.ShellScope.BeforeDisposeAsync()
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute, Boolean activateShell)
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute, Boolean activateShell)
   at OrchardCore.Modules.ModularTenantContainerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)    
   at OrchardCore.Environment.Shell.Scope.ShellScope.BeforeDisposeAsync()
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute, Boolean activateShell)
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute, Boolean activateShell)
   at OrchardCore.Modules.ModularTenantContainerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)

   
2025-05-18 13:08:36.1195|Default|00-7698c87ab758c47f61a3a49cb5750f29-efb5ea0bc6ac562d-00|2|Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware|WARN|The response has already started, the error page middleware will not be executed. 

2025-05-18 13:08:36.1195|Default|00-7698c87ab758c47f61a3a49cb5750f29-efb5ea0bc6ac562d-00|13|Microsoft.AspNetCore.Server.Kestrel|ERROR|Connection id "0HNCLPSFARDRK", Request id "0HNCLPSFARDRK:00000057": An unhandled exception was thrown by the application. System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at OrchardCore.Environment.Shell.Scope.ShellScope.BeforeDisposeAsync()
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute, Boolean activateShell)
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute, Boolean activateShell)
   at OrchardCore.Modules.ModularTenantContainerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Watch.BrowserRefresh.BrowserRefreshMiddleware.InvokeAsync(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)    at OrchardCore.Environment.Shell.Scope.ShellScope.BeforeDisposeAsync()
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute, Boolean activateShell)
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute, Boolean activateShell)
   at OrchardCore.Modules.ModularTenantContainerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Watch.BrowserRefresh.BrowserRefreshMiddleware.InvokeAsync(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

### PR DESCRIPTION
**Pull request by gvkries**
Fixes #17930

### CODE REVIEW

File: src/OrchardCore/OrchardCore.Abstractions/Shell/Scope/ShellScope.cs [hunk 1]
```diff
@@ -621,8 +637,27 @@ private void Terminate()
...
     }
+
+    [Flags]
+    private enum ShellScopeStates : byte
+    {
+        ServiceScopeOnly = 0b0000_0001,
+        ShellTerminated = 0b0000_0010,
+        IsTerminating = 0b0000_0100,
+        Terminated = 0b0000_1000,
+        IsDisposed = 0b0001_0000,
```
Comment (sebastienros) [inline src/OrchardCore/OrchardCore.Abstractions/Shell/Scope/ShellScope.cs:661]:
```suggestion
        ServiceScopeOnly = 1,
        ShellTerminated = 2,
        IsTerminating = 4,
        Terminated = 8,
        IsDisposed = 16,
```

File: src/OrchardCore/OrchardCore.Data.YesSql/OrchardCoreBuilderExtensions.cs [hunk 2]
```diff
@@ -151,19 +151,24 @@ public static OrchardCoreBuilder AddDataAccess(this OrchardCoreBuilder builder)
...
-                    {
-                        return scope.ServiceProvider
-                            .GetRequiredService<IDocumentStore>()
-                            .CancelAsync();
-                    });
+                // Register automated document store commit and rollback when the ISession is used
+                // on the DI scope of the shell. All other scopes will not be automatically committed.
+                if (sp == ShellScope.Current?.ServiceProvider)
+                {
+                    ShellScope.Current
```
Comment (sebastienros) [inline src/OrchardCore/OrchardCore.Data.YesSql/OrchardCoreBuilderExtensions.cs:158]: Reuse value
