### PR TITLE
CultureAspect must work for localization & content localization modules

### LINKED ISSUE #4229: input control alignment in RTL is wrong
Capture

in RTL  the input value is aligned to left, it should be right-aligned.

### PR DESCRIPTION
**Pull request by hishamco**
Fix #4229

This should work now for both localization & content localization module

### CODE REVIEW

**Comment by deanmarcussen** [comment]
> Is this mean for tenant other than default tenant?!!

I assume everything is meant for multiple tenant support? Is that wrong?
You can try it.

Setup a sass host, leave the host culture as en-US.
Setup a tenant, add a RTL culture.
Remove en-US.
See if it works

**Comment by hishamco** [comment]
Sorry I blocked by the environment, after 3.0.0, hope the project works soon, after that I will look into all the PRs that's related to me

**Comment by hishamco** [comment]
@deanmarcussen I can confirm it's working, with the above scenario too

**Comment by deanmarcussen** [comment]
@hishamco Cool, if you have tested and it's working good, that's enough for me

File: src/OrchardCore/OrchardCore.Localization.Abstractions/CultureAspect.cs [hunk 1]
```diff
@@ -7,11 +7,9 @@ namespace OrchardCore.Localization
     /// </summary>
     public class CultureAspect
     {
-        private static readonly CultureInfo _defaultCulture = CultureInfo.InstalledUICulture ?? CultureInfo.InvariantCulture;
-
         /// <summary>
         /// Gets or sets the culture.
         /// </summary>
-        public CultureInfo Culture { get; set; } = _defaultCulture;
+        public CultureInfo Culture { get; set; } = CultureInfo.CurrentUICulture;
```
Comment (hishamco) [inline src/OrchardCore/OrchardCore.Localization.Abstractions/CultureAspect.cs:13]: @Skrypt look who did this here 🤦‍♂ but even the default behavior will return a default culture, seems we did something wrong here ;)

This mean it will assign the default culture even if the content item doesn't have a `LocalizationPart` which is wrong, it should be `null`, @sebastienros do you remember why we doing thing? Coz I'm facing an issue in Lucene module right now, but I did a workaround, sooner or later we should fix this without impact other places
