### PR TITLE
Fix DefaultHtmlDisplay's ShapeDescriptor resolution

### LINKED ISSUE #4713: Templates module overrides fundamental shapes
If you try to override a base template in Templates module (i.e. : Menu, Content…) it overrides the base shape descriptor. So, handlers ('CreatingAsync', 'CreatedAsync', …) are not called.

Result :
- 'Menu' template will always be empty
- 'Content' template will disable `DisplayType` and content `Id` based alternates

Not tested, but probably same issue with pager shapes...

### PR DESCRIPTION
**Pull request by TFleury**
Fixes #4713 & #3145

Also removes useless ShapeDescriptor property from ShapeBinding, which leads to some simplifications.

### CODE REVIEW

**Comment by jtkech** [comment]
Wow, awesome but not obvious to remind me all details.

My only concern is to be sure that there is no difference in some cases to 1st search a shape descriptor in place of searching a binding. Hmm, then we use the shape descriptor of this binding, it seems you are right, for a given shape type it should be the same. And further you search for an `actualBinding` (as before) when we really use it (not its descriptor).

So LGTM

File: src/OrchardCore/OrchardCore.DisplayManagement/Implementation/DefaultHtmlDisplay.cs [hunk 1]
```diff
@@ -176,6 +176,26 @@ public async Task<IHtmlContent> ExecuteAsync(DisplayContext context)
             return shape.Metadata.ChildContent;
         }
 
+        private ShapeDescriptor GetShapeDescriptor(string shapeType, ShapeTable shapeTable)
+        {
+            var shapeTypeScan = shapeType;
+            for (; ; )
```
Comment (hishamco) [inline src/OrchardCore/OrchardCore.DisplayManagement/Implementation/DefaultHtmlDisplay.cs]: Is this by intention?!! if it's we could format or use `while` instead

File: test/OrchardCore.Tests/DisplayManagement/DefaultDisplayManagerTests.cs [hunk 2]
```diff
@@ -27,17 +29,21 @@ public DefaultDisplayManagerTests()
                 Bindings = new Dictionary<string, ShapeBinding>(StringComparer.OrdinalIgnoreCase)
             };
 
+            _additionalBindings = new TestShapeBindingsDictionary();
+
```
Comment (hishamco) [inline test/OrchardCore.Tests/DisplayManagement/DefaultDisplayManagerTests.cs]: Remove extra line

File: test/OrchardCore.Tests/DisplayManagement/DefaultDisplayManagerTests.cs [hunk 3]
```diff
@@ -94,6 +99,28 @@ public async Task RenderSimpleShape()
             Assert.Equal("Hi there!", result.ToString());
         }
 
+        [Fact]
+        public async Task RenderIShapeBindingResolverProvidedShapes()
+        {
+            var displayManager = _serviceProvider.GetService<IHtmlDisplay>();
+
```
Comment (hishamco) [inline test/OrchardCore.Tests/DisplayManagement/DefaultDisplayManagerTests.cs]: Extra line

File: test/OrchardCore.Tests/DisplayManagement/DefaultDisplayManagerTests.cs [hunk 4]
```diff
@@ -94,6 +99,28 @@ public async Task RenderSimpleShape()
...
+            var shape = new Shape();
+            shape.Metadata.Type = "Baz";
+
```
Comment (hishamco) [inline test/OrchardCore.Tests/DisplayManagement/DefaultDisplayManagerTests.cs]: Also here

File: src/OrchardCore/OrchardCore.DisplayManagement/Descriptors/ShapeTable.cs [hunk 5]
```diff
@@ -94,7 +94,6 @@ public bool TryGetValue(string shapeAlternate, out ShapeBinding binding)
                 {
                     binding = new ShapeBinding
                     {
-                        ShapeDescriptor = descriptor,
```
Comment (sebastienros) [inline src/OrchardCore/OrchardCore.DisplayManagement/Descriptors/ShapeTable.cs]: I remember when I added it, it was to be able to find the source of a shape when I developed the Shape Tracing tool. I feel better we get rid of it to be honest ...

File: src/OrchardCore/OrchardCore.DisplayManagement/Implementation/DefaultHtmlDisplay.cs [hunk 6]
```diff
@@ -257,6 +265,17 @@ static IHtmlContent CoerceHtmlString(object value)
             return new HtmlString(HtmlEncoder.Default.Encode(value.ToString()));
         }
 
+        private static bool TryGetParentShapeTypeName(ref string shapeTypeScan)
```
Comment (sebastienros) [inline src/OrchardCore/OrchardCore.DisplayManagement/Implementation/DefaultHtmlDisplay.cs]: What's the point of the `ref` argument? strings are already passed by ref.

Comment (TFleury) [reply src/OrchardCore/OrchardCore.DisplayManagement/Implementation/DefaultHtmlDisplay.cs]: It's to assign the parent shape type name to `shapeTypeScan`.

Comment (sebastienros) [reply src/OrchardCore/OrchardCore.DisplayManagement/Implementation/DefaultHtmlDisplay.cs]: Not a pattern we use a lot, but I understand now. We usually prefer `out` arguments in this case. You choose.

Comment (TFleury) [reply src/OrchardCore/OrchardCore.DisplayManagement/Implementation/DefaultHtmlDisplay.cs]: I think I never used it before, but `out` switch dont requires the parameter to be assigned and requires to assign it in all cases. So `ref` is the most suitable.
