### PR TITLE
Associate shapes build from template files to all enabled features

### LINKED ISSUE #18364: Missing shape in `ShapeTable`
### Discussed in https://github.com/OrchardCMS/OrchardCore/discussions/18342

<div type='discussions-op-text'>

<sup>Originally posted by **PiemP** September 11, 2025</sup>
Hello,

I'm encountering a recurring issue with OrchardCore 2.1.7.

I've created several custom shapes across different modules. My application runs with a SaaS recipe, and to reproduce the issue, I've created 22 tenants in my local environment.

I'm using IIS 10 as the application server, but I've also reproduced the issue on my local laptop.

When I recycle the application pool, some shapes are not loaded into the ShapeTable object. This only happens in certain tenants, not all of them.

Is it possible for this to happen? I'm asking because if I perform another recycle, the shapes are correctly loaded.

Any help would be greatly appreciated.</div>

### PR DESCRIPTION
**Pull request by gvkries**
Fixes #18364

### CODE REVIEW

File: src/OrchardCore/OrchardCore.DisplayManagement/Descriptors/ShapeTemplateStrategy/ShapeTemplateBindingStrategy.cs [hunk 1]
```diff
@@ -116,30 +116,31 @@ public override async ValueTask DiscoverAsync(ShapeTableBuilder builder)
...
+                    .BoundAs(
+                        hit.shapeContext.harvestShapeInfo.RelativePath, displayContext =>
+                        {
+                            var viewEngine = displayContext.ServiceProvider
+                                .GetServices<IShapeTemplateViewEngine>()
+                                .FirstOrDefault(e => e.GetType() == viewEngineType);
 
-                        return viewEngine.RenderAsync(hit.shapeContext.harvestShapeInfo.RelativePath, displayContext);
-                    });
+                            return viewEngine.RenderAsync(hit.shapeContext.harvestShapeInfo.RelativePath, displayContext);
```
Comment (infofromca) [inline src/OrchardCore/OrchardCore.DisplayManagement/Descriptors/ShapeTemplateStrategy/ShapeTemplateBindingStrategy.cs]: return viewEngine?.RenderAsync(hit.shapeContext.harvestShapeInfo.RelativePath, displayContext);

Comment (gvkries) [reply src/OrchardCore/OrchardCore.DisplayManagement/Descriptors/ShapeTemplateStrategy/ShapeTemplateBindingStrategy.cs]: Maybe it's even better to use `Single`...

**Review by sebastienros — APPROVED** [review]

**Comment by gvkries** [comment]
@sebastienros @MikeAlhayek I've removed the `Once` method as we talked about yesterday. Also done some minor improvements to the `ShapeTemplateBindingStrategy`.
