### PR TITLE
Fixes AntiforgeryValidationException

### LINKED ISSUE #3293: AntiforgeryValidationException on setup screen
1. Open the freshly cloned solution in VS.
2. Run via IIS Express with Ctrl + F5.
3. Once the setup screen loads the following exception will be logged:

> 2019-03-07 21:46:19.1911|Default|80000020-0003-ff00-b63f-84710c7967bb||Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgery|ERROR|An exception was thrown while deserializing the token. Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: The antiforgery token could not be decrypted. ---> System.Security.Cryptography.CryptographicException: The key {d5291043-225b-445d-96a0-5f37ab41318c} was not found in the key ring.
>    at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
>    at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.DangerousUnprotect(Byte[] protectedData, Boolean ignoreRevocationErrors, Boolean& requiresMigration, Boolean& wasRevoked)
>    at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
>    at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
>    --- End of inner exception stack trace ---
>    at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
>    at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgery.GetCookieTokenDoesNotThrow(HttpContext httpContext)    at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
>    at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgery.GetCookieTokenDoesNotThrow(HttpContext httpContext)

If you start the app again then this won't happen, but you can get it again if you delete the App_Data folder.

Since this exception is swalloed and doesn't cause the setup to fail (you can set up the site without issues) it's not a huge deal. Nertheless not ideal.

Latest dev (eda45527dbc077b40932fe7cdbe37df204013465). CC @barthamark

### PR DESCRIPTION
**Pull request by jtkech**
Fixes #3293

We fixed it on a new setup but we still have errors logged when we run an application from a given location and login to the admin, and then do the same from another application location but same url.

Using this in the startup seems to fix the issue but then you get a new cookie on each startup

    var cookieName = "orchantiforgery_" + settings.Name + Guid.NewGuid().ToString();

So i suggest the following that only add a cookie per application location and that also works

    var cookieName = "orchantiforgery_" + settings.Name + env.ContentRootPath;

### CODE REVIEW

File: src/OrchardCore/OrchardCore/Modules/Extensions/ServiceCollectionExtensions.cs [hunk 1]
```diff
@@ -245,8 +245,9 @@ private static void AddAntiForgery(OrchardCoreBuilder builder)
             builder.ConfigureServices((services, serviceProvider) =>
             {
                 var settings = serviceProvider.GetRequiredService<ShellSettings>();
+                var environment = serviceProvider.GetRequiredService<IHostEnvironment>();
 
-                var cookieName = "orchantiforgery_" + settings.Name;
+                var cookieName = "orchantiforgery_" + settings.Name + environment.ContentRootPath;
```
Comment (sebastienros) [inline src/OrchardCore/OrchardCore/Modules/Extensions/ServiceCollectionExtensions.cs]: Doesn't it need to be url encoded?

Comment (jtkech) [reply src/OrchardCore/OrchardCore/Modules/Extensions/ServiceCollectionExtensions.cs]: Yes, but as i saw it is done automatically by aspnetcore

But just quickly done, maybe better to do it explicitly, will do

**Comment by jtkech** [comment]
Done, we explicitly url encode the whole tenant name + location, also the tenant name that may have special character, as i already did for the `orchauth_` cookie in the `OC.Users` startup.
