### PR TITLE
Fix Get not returning changes made be Apply

### LINKED ISSUE #3366: ContentExtension.Apply does not update the Elements cache.
ContentExtension.Apply does not update the Elements cache when merging. This results in subsequent calls to Get returning the wrong data

Quick fix would be to Remove the element.

### PR DESCRIPTION
**Pull request by PaulEpitomy**
fixes #3366

### CODE REVIEW

**Comment by sebastienros** [comment]
I really appreciate the UT, could you also share how you reproduced this in the Admin UI so I can understand what is currently broken?

**Comment by PaulEpitomy** [comment]
This is from custom module. The module makes use of Alter to merge data from an external system to dynamically created (in memory) ContentItems

**Comment by sebastienros** [comment]
I think we should also update the second `Apply` method to do the same. Can you do it?

File: src/OrchardCore/OrchardCore.ContentManagement.Abstractions/ContentExtensions.cs [hunk 1]
```diff
@@ -148,6 +148,7 @@ public static ContentElement Apply(this ContentElement contentElement, string na
             if (elementData != null)
             {
                 elementData.Merge(JObject.FromObject(element), JsonMergeSettings);
+                contentElement.Elements.Remove(name);
```
Comment (sebastienros) [inline src/OrchardCore/OrchardCore.ContentManagement.Abstractions/ContentExtensions.cs]: This could be an issue if you have some state on the element that is not in the jobject (the reason we made the `Elements` map).

Comment (sebastienros) [reply src/OrchardCore/OrchardCore.ContentManagement.Abstractions/ContentExtensions.cs]: Should we replace the existing element with the one passed as an argument instead? That might be less wrong.

Comment (PaulEpitomy) [reply src/OrchardCore/OrchardCore.ContentManagement.Abstractions/ContentExtensions.cs]: Replacing it seems a better option, Id assumed the merge applied to the ContentItem not the ContentElement so a complete replacement of the ContentElement makes sense.

I'll fix the other `Appy ` tomorrow.

Comment (sebastienros) [reply src/OrchardCore/OrchardCore.ContentManagement.Abstractions/ContentExtensions.cs]: Then I will do it now ;) and you can approve/disapprove
