### PR TITLE
Use JsonPath.Net for JSONPath selectors (Lombiq Technologies: OCORE-148)

### LINKED ISSUE #15497: Can't delete menu items on the latest preview
### Describe the bug
Deleting seemingly succeeds but has no effect. I've tested it on the current dev branch as well as a fairly recent preview cloudsmith package of OC with Lombiq.OSOCE.

### To Reproduce
1. Create a new site with the Blog recipe.
2. Go to Admin > Main Menu.
3. Click the Delete button next to an already existing menu item like "About", and then click "Ok".
4. Page loads with the success message "Menu item deleted successfully." but the "About" item is still present.
5. Go to the home page.
6. "About" link is still present.

### Expected behavior
Item should be removed from the menu.

### LINKED ISSUE #15505: Inconsistent JObject.SelectNode() behavior and feature loss
### Describe the bug

I have a few concerns with the new `JObject.SelectNode()` extension method:

If you try to use it on a content part's `Content` property, it won't work unless you re-serialize the JSON object first, e.g.:
```csharp
var content = (JsonObject)contentElement.Content;
content.SelectNode(path); // This is null.
JsonSerializer.SerializeToNode(content).SelectNode(path); // This is not null.
```

Also you can't chain `SelectNode` calls, the second call will still search from the same position, e.g.:
image

I think when you query a `JsonObject`, it tries to query from its document root instead of the current element. This is unexpected.

Finally, I'm not sure if anyone is affected, but after the migration to STJ we have lost full compliant JSONPath query support. The documentation of `JObject.SelectNode()` extension method [claims that it searches using "a JSON path"](https://github.com/OrchardCMS/OrchardCore/blob/50583b0644fe90f0a7253c78885504c910c4175a/src/OrchardCore/OrchardCore.Abstractions/Json/Nodes/JObject.cs#L89), however this is misleading because it's compliant with [the JSONPath specification](https://www.ietf.org/archive/id/draft-goessner-dispatch-jsonpath-00.html). An example of a query that should work but doesn't (using the same JSON as above):

```csharp
var data = JsonNode.Parse("{\"SelectedContentItem\":{\"ContentItemIds\":[\"48yrgcwkhv7hkwarvtzpw3ccms\"]},\"Name\":\"My Content\"}");
data.SelectNode("SelectedContentItem.ContentItemIds"); // works, result: [ "48yrgcwkhv7hkwarvtzpw3ccms" ]
data.SelectNode("$.SelectedContentItem.ContentItemIds"); // works, result: [ "48yrgcwkhv7hkwarvtzpw3ccms" ]
data.SelectNode("$..ContentItemIds"); // doesn't work, result is null but it should be the same as above
```
You can verify that the last one should work using the [JSONPath Online Evaluator](https://jsonpath.com/):
image Also it works with Newtonsoft:

image

### Expected behavior

- `SelectNode` should query from the current element.
- Ideally it should keep supporting full JSONPath.

### Suggestion

Beyond fixing `JObject.SelectNode` to search from the current node, the documentation should be updated:
- The documentation comment I linked above should include a `<remarks>` section explaining what is and what isn't supported by the current implementation.
- The 1.9 release notes should mention this breaking change in [the "Drop Newtonsoft.Json Support" section](https://github.com/OrchardCMS/OrchardCore/blob/50583b0644fe90f0a7253c78885504c910c4175a/src/docs/releases/1.9.0.md#drop-newtonsoftjson-support).

Consider if there is a JSONPath library we can use instead of a homebrew implementation. I haven't used it yet, but [JsonPath.Net](https://www.nuget.org/packages/JsonPath.Net/0.1.3) of the [json-everything](https://github.com/gregsdennis/json-everything) project might be suitable? It's for STJ, MIT licensed and it seems to be actively maintained.

### PR DESCRIPTION
**Pull request by sarahelsaig**
Fixes #15505

### CODE REVIEW

**Comment by Piedone** [comment]
@MikeAlhayek could you please check?

File: src/OrchardCore/OrchardCore.Abstractions/Json/Nodes/JNode.cs [hunk 1]
```diff
@@ -170,26 +171,25 @@ public static bool TryParse(string json, out JsonNode? jsonNode, JsonNodeOptions
...
-            return jsonObject.SelectNode(path);
-        }
-
-        if (jsonNode is JsonArray jsonArray)
-        {
-            return jsonArray.SelectNode(path);
-        }
+        path = path?.Trim();
+        if (string.IsNullOrEmpty(path)) return jsonNode;
+        if (path[0] != '$') path = "$." + path;
```
Comment (MikeAlhayek) [inline src/OrchardCore/OrchardCore.Abstractions/Json/Nodes/JNode.cs:188]:
```suggestion
        if (string.IsNullOrEmpty(path)) {
            return jsonNode;
        }
        
        if (path[0] != '$') {
            path = "$." + path;
        }
```

File: test/OrchardCore.Tests/Data/ContentItemTests.cs [hunk 2]
```diff
@@ -101,6 +94,43 @@ public void ContentShouldStoreFields()
...
+            AssertJsonEqual(textPropertyNode, contentPartJson.SelectNode("Text"));
+            AssertJsonEqual(textPropertyNode, contentItemJson.SelectNode("MyPart.Text"));
+            AssertJsonEqual(textPropertyNode, contentItemJson.SelectNode("$..Text"));
+        }
+
+        private static ContentItem CreateContentItemWithPart(string text = "test")
+        {
+            var contentItem = new ContentItem();
+            contentItem.GetOrCreate<MyPart>();
+            contentItem.Alter<MyPart>(x => x.Text = text);
```
Comment (MikeAlhayek) [inline test/OrchardCore.Tests/Data/ContentItemTests.cs:124]:
```suggestion
            contentItem.Alter<MyPart>(x => x.Text = text);
            
```

**Review by MikeAlhayek — CHANGES_REQUESTED** [review]
I would request a review from @sebastienros for this one.

File: src/OrchardCore/OrchardCore.Abstractions/Json/Nodes/JNode.cs (hunk 1 above)
Comment (sebastienros) [reply src/OrchardCore/OrchardCore.Abstractions/Json/Nodes/JNode.cs:188]: It's orchard core, we put open braces on new lines ;)

Comment (sebastienros) [inline src/OrchardCore/OrchardCore.Abstractions/Json/Nodes/JNode.cs:188]: is not using `$.` not supported in JSONPath.Net?
Ideally we would not patch what the caller specifies, but if we are using something that is currently incompatible, and JSONPath.NEt doesn't support it then fine. Add a comment in that case.

File: test/OrchardCore.Tests/Data/ContentItemTests.cs [hunk 3]
```diff
@@ -46,9 +47,7 @@ public void ShouldSerializeParts()
         [Fact]
         public void ShouldUpdateContent()
         {
-            var contentItem = new ContentItem();
-            contentItem.GetOrCreate<MyPart>();
-            contentItem.Alter<MyPart>(x => x.Text = "test");
+            var contentItem = CreateContentItemWithPart();
```
Comment (sebastienros) [inline test/OrchardCore.Tests/Data/ContentItemTests.cs:50]: I personally like code duplication when it's small, it talks for itself, doesn't need me to jump to some other places or if I am lazy not understand what it actually does.

File: src/OrchardCore/OrchardCore.Abstractions/Json/Nodes/JNode.cs [hunk 4]
```diff
@@ -170,26 +171,25 @@ public static bool TryParse(string json, out JsonNode? jsonNode, JsonNodeOptions
...
-    public static JsonNode? SelectNode(this JsonNode? jsonNode, string? path)
+    /// <param name="jsonNode">The JSON node which serves as the root of the current search..</param>
+    /// <param name="path">The JSONPath query where <c>$</c> is <paramref name="jsonNode"/>.</param>
+    /// <param name="options">Optional settings to configure the JSONPath parser.</param>
+    /// <remarks>
+    /// This method uses JsonPath.Net to evaluate the <paramref name="path"/>. For more information on JSONPath, see the
+    /// specification at https://www.rfc-editor.org/rfc/rfc9535.html or the JsonPath.Net documentation at
+    /// https://docs.json-everything.net/path/basics/.
+    /// </remarks>
+    public static JsonNode? SelectNode(this JsonNode? jsonNode, string? path, PathParsingOptions? options = null)
```
[the remark this answers is not in the document]
Comment (sebastienros) [reply src/OrchardCore/OrchardCore.Abstractions/Json/Nodes/JNode.cs:184]: I realized it was there before, it should still be fixed IMO.

File: src/OrchardCore/OrchardCore.Abstractions/Json/Nodes/JNode.cs (hunk 1 above)
Comment (MikeAlhayek) [reply src/OrchardCore/OrchardCore.Abstractions/Json/Nodes/JNode.cs:188]: Duh! lol

File: test/OrchardCore.Tests/Data/ContentItemTests.cs (hunk 3 above)
Comment (MikeAlhayek) [reply test/OrchardCore.Tests/Data/ContentItemTests.cs:50]: Counter argument: If you create a good method name, the name should tell you what it does without having to duplicate code or guess

Comment (sebastienros) [reply test/OrchardCore.Tests/Data/ContentItemTests.cs:50]: Agreed. In that case, and because I don't use this API much, it felt good to understand what it meant to create a content item and add a part. And then the statements after with .Alter had more meaning in this context

File: src/OrchardCore/OrchardCore.Abstractions/Json/Nodes/JNode.cs (hunk 4 above)
[the remark this answers is not in the document]
Comment (sarahelsaig) [reply src/OrchardCore/OrchardCore.Abstractions/Json/Nodes/JNode.cs:184]: Nullability was already enabled in this file [here](https://github.com/OrchardCMS/OrchardCore/blob/1721fbb5e7a61f16a607a9ba8654182d1b9dac1a/src/OrchardCore/OrchardCore.Abstractions/Json/Nodes/JNode.cs#L9). I agree, `jsonNode`˙and `path` shouldn't be nullable (but `options` should, ofc). Fixed.

File: src/OrchardCore/OrchardCore.Abstractions/Json/Nodes/JNode.cs (hunk 1 above)
Comment (sarahelsaig) [reply src/OrchardCore/OrchardCore.Abstractions/Json/Nodes/JNode.cs]: It's not supported. (afaik paths without the leading `$` is non-spec in JSONPath) Without that condition `JsonPath.TryParse` returns false, and `JsonPath.Parse(path)` throws:
```
Json.Path.PathParseException: Path must start with '$'
   at Json.Path.PathParser.Parse(ReadOnlySpan`1 source, Int32& index, PathParsingOptions options, Boolean requireGlobal)
   at Json.Path.JsonPath.Parse(String source, PathParsingOptions options)
```
Based on the exception message, this patch should be universally safe.

I believe in Newtonsoft does this automatically under the hood. You can see from this example, that the path `property` behaves as `$.property` and not as `$..property`.

image

I agree that it's not ideal, but without this patch existing functionality in OC would break.

File: test/OrchardCore.Tests/Data/ContentItemTests.cs (hunk 3 above)
Comment (MikeAlhayek) [reply test/OrchardCore.Tests/Data/ContentItemTests.cs:50]: maybe rename `CreateContentItemWithPart` to `CreateContentItemWithMyPart`

Comment (sarahelsaig) [reply test/OrchardCore.Tests/Data/ContentItemTests.cs:50]: When I was about to add a test, knowing if each test's setup section was identical or not was more important than the specifics. I had to stop and compare methods, which I didn't enjoy. So it wasn't just DRY for DRY's sake.

**Review by sebastienros — APPROVED** [review]

**Comment by MikeAlhayek** [comment]
@sarahelsaig can you please fix the conflict here so we can merge it?
