### PR TITLE
Check if element type is as requested

### LINKED ISSUE #15973: Getting content element by name and type can fail even if valid
### Describe the bug
When you try to get some content part lets say BlogPart from content item you can use extension method ContentExtensions.Get . Bug occurs when there are multiple valid casts of content part.
### To Reproduce
1. make a Blog content item with BlogPart
2. in code get content part as ContentPart (base class of every part) `contentItem.Get<ContentPart>("BlogPart")`
3. then try to get content part as BlogPart `contentItem.Get<BlogPart>("BlogPart")`
4. InvalidCastException

### Expected behavior
casts are valid should recast object

### PR DESCRIPTION
**Pull request by tropcicstefan**
Fixes #15973

### CODE REVIEW

File: src/OrchardCore/OrchardCore.ContentManagement.Abstractions/ContentExtensions.cs [hunk 1]
```diff
@@ -65,7 +65,10 @@ public static ContentElement Get(this ContentElement contentElement, Type conten
         {
             if (contentElement.Elements.TryGetValue(name, out var element))
             {
-                return element;
+                if (element.GetType() == contentElementType)
```
Comment (MikeAlhayek) [inline src/OrchardCore/OrchardCore.ContentManagement.Abstractions/ContentExtensions.cs:68]: I don't think we should guard here against invalid usage. I would say make sure you are calling the method correctly to begin with

Comment (gvkries) [reply src/OrchardCore/OrchardCore.ContentManagement.Abstractions/ContentExtensions.cs:68]: I think the idea is not that bad, but we could instead allow deserializing a more specific type here, e.g. something like this:

```C#
if (contentElement.Elements.TryGetValue(name, out var element))
{
    var currentType = element.GetType();

    if (currentType == contentElementType ||
        !currentType.IsAssignableFrom(contentElementType))
        return element;
}
[...]
```

Comment (MikeAlhayek) [reply src/OrchardCore/OrchardCore.ContentManagement.Abstractions/ContentExtensions.cs:68]: maybe without the or?

Comment (gvkries) [reply src/OrchardCore/OrchardCore.ContentManagement.Abstractions/ContentExtensions.cs:68]: Hmm, shouldn't it immediately throw if the type is invalid?

Comment (MikeAlhayek) [reply src/OrchardCore/OrchardCore.ContentManagement.Abstractions/ContentExtensions.cs:68]: The main problem here is that the invalid use will not always cause the serialize and not take advantage of the cache. Someone **unknowingly** can be following invalid use and not take advantage of caching.

Comment (gvkries) [reply src/OrchardCore/OrchardCore.ContentManagement.Abstractions/ContentExtensions.cs:68]: Yes, my idea was just to allow derived types to deserialize again, otherwise either return the previously deserialized instance (as before) or (maybe better) throw an `InvalidCastException` like the generic `Get<T>()` method.

Comment (MikeAlhayek) [reply src/OrchardCore/OrchardCore.ContentManagement.Abstractions/ContentExtensions.cs:68]: I don't have strong opinion here. Personally, I rather not encourage bad practice. @Piedone @hishamco thoughts on this PR?

Comment (sebastienros) [reply src/OrchardCore/OrchardCore.ContentManagement.Abstractions/ContentExtensions.cs:68]: Combine the condition with the `TryGetValue`, and use `IsAssignableTo` instead of type==type such that base types would work, e.g. calling BlogPart THEN ContentPart would then work as an instance of BlogPart "is assignable to" ContentPArt.

Add the unit test from @gvkries and another one that does the BlogPart "then" ContentPart calls.

Comment (Piedone) [reply src/OrchardCore/OrchardCore.ContentManagement.Abstractions/ContentExtensions.cs:68]: I agree with that.

An alternative can be to use type+name as the `Elements` key. However, this would require changes to all the other `Elements` accesses in the class. And I'm not sure if the frequency of the use case (i.e. `Get`ting the same content part of the same content item object with different types) warrants anything more complex.

**Comment by MikeAlhayek** [comment]
@tropcicstefan I made direct changes to your branch.
