### PR TITLE
Keep IDisplayManager backward compatible

### LINKED ISSUE #12678: Breaking changes in DisplayManager in 1.5
### Describe the bug

I am using `BuildEditor` of `DisplayManager` to create a shape, It's working well, but when upgraded to 1.5 preview feed started getting following error.

image

### PR DESCRIPTION
**Pull request by ns8482e**
Added method overload to avoid method not found exception in modules that depends on IDisplayManager
//cc @jtkech @MikeAlhayek @hishamco 

Fixes #12678

### CODE REVIEW

**Comment by MikeAlhayek** [comment]
@ns8482e I don't know how I feel about this change. your overloading the interface. What if you add the previous overload with as an extension method with the same name space as the interface?

Something like this

```
public static class DisplayManagerExtensions
{
	public static Task<IShape> BuildEditorAsync(this IDisplayManager displayManager, TModel model, IUpdateModel updater, bool isNew, string group = null)
		=> displayManager.BuildEditorAsync(model, updater, isNew, group, String.Empty);
	

	public static Task<IShape> UpdateEditorAsync(this IDisplayManager displayManager, TModel model, IUpdateModel updater, bool isNew, string groupId = "")
            => displayManager.UpdateEditorAsync(model, updater, isNew, groupId, String.Empty, String.Empty);
}
```

**Comment by ns8482e** [comment]
@MikeAlhayek i am not overwriting interface I am reverting change made to interface in PR #11775  to keep interface unchanged between 1.4 and 1.5

**Comment by MikeAlhayek** [comment]
You are adding 2 new signatures to the interface. If anyone is implementing this interface will have the same problem you started with. Except their app will break since the new methods are not implemented. Look into using extensions as I mentioned last and see if that'll fix your issue.

**Comment by ns8482e** [comment]
> What if you add the previous overload with as an extension method with the same name space as the interface?

Extension won’t help as it still requires existing module to recompile, the module compiled against 1.4 expects method in interface

**Comment by ns8482e** [comment]
> You are adding 2 new signatures to the interface. If anyone is implementing this interface will have the same problem you started with. 

we are adding new method in interface in 1.5, if someone is implementing their own flavor of DisplayManager then they will have to implement new methods added  in interface in 1.5

However the real issue here is consumer of IDisplayManager which is injected in client code that using OC provided DisplayManager implementation.

**Review by jtkech — APPROVED** [review]

**Review by Skrypt — APPROVED** [review]

File: src/OrchardCore/OrchardCore.DisplayManagement/IDisplayManager.cs [hunk 1]
```diff
@@ -6,7 +6,15 @@ namespace OrchardCore.DisplayManagement
     public interface IDisplayManager<TModel>
     {
         Task<IShape> BuildDisplayAsync(TModel model, IUpdateModel updater, string displayType = "", string groupId = "");
-        Task<IShape> BuildEditorAsync(TModel model, IUpdateModel updater, bool isNew, string groupId = "", string htmlPrefix = "");
-        Task<IShape> UpdateEditorAsync(TModel model, IUpdateModel updater, bool isNew, string groupId = "", string htmlPrefix = "");
+
+        Task<IShape> BuildEditorAsync(TModel model, IUpdateModel updater, bool isNew, string groupId = "")
```
Comment (sebastienros) [inline src/OrchardCore/OrchardCore.DisplayManagement/IDisplayManager.cs:10]: Can we make these obsolete such that old compiled libraries use the obsolete methods, but new code knows it should use the new methods.

Comment (ns8482e) [reply src/OrchardCore/OrchardCore.DisplayManagement/IDisplayManager.cs:10]: No need to make it obsolete as its just an overloading

Comment (ns8482e) [reply src/OrchardCore/OrchardCore.DisplayManagement/IDisplayManager.cs:10]: Also you can't `obsolete` exiting and add new method with default param as you can't compile the code as compiler complains about ambiguous error

Comment (sebastienros) [reply src/OrchardCore/OrchardCore.DisplayManagement/IDisplayManager.cs:10]: Seems to build with this:

```c#
using System;
using System.Threading.Tasks;
using OrchardCore.DisplayManagement.ModelBinding;

namespace OrchardCore.DisplayManagement
{
    public interface IDisplayManager<TModel>
    {
        Task<IShape> BuildDisplayAsync(TModel model, IUpdateModel updater, string displayType = "", string groupId = "");
        Task<IShape> BuildEditorAsync(TModel model, IUpdateModel updater, bool isNew, string groupId, string htmlPrefix);
        Task<IShape> UpdateEditorAsync(TModel model, IUpdateModel updater, bool isNew, string groupId, string htmlPrefix);

        [Obsolete]
        Task<IShape> BuildEditorAsync(TModel model, IUpdateModel updater, bool isNew, string groupId = "")
            => BuildEditorAsync(model, updater, isNew, groupId, "");

        [Obsolete]
        Task<IShape> UpdateEditorAsync(TModel model, IUpdateModel updater, bool isNew, string groupId = "")
            => UpdateEditorAsync(model, updater, isNew, groupId, "");
    }
}

```

There are warning that can be fixed by using the new methods explicitly.

Comment (hishamco) [reply src/OrchardCore/OrchardCore.DisplayManagement/IDisplayManager.cs:10]: @MikeAlhayek which if them you added in `1.4`?

Comment (MikeAlhayek) [reply src/OrchardCore/OrchardCore.DisplayManagement/IDisplayManager.cs:10]: The once’s with the prefix

Comment (hishamco) [reply src/OrchardCore/OrchardCore.DisplayManagement/IDisplayManager.cs:10]: I see, I though the obsolete once

Comment (ns8482e) [reply src/OrchardCore/OrchardCore.DisplayManagement/IDisplayManager.cs:14]: @sebastienros agree, updated as suggested

**Review by MikeAlhayek — APPROVED** [review]

**Comment by ns8482e** [comment]
@sebastienros Removed warnings

File: src/OrchardCore.Modules/OrchardCore.AdminMenu/Controllers/NodeController.cs [hunk 2]
```diff
@@ -220,7 +220,7 @@ public async Task<IActionResult> Edit(AdminNodeEditViewModel model)
                 return NotFound();
             }
 
-            var editor = await _displayManager.UpdateEditorAsync(treeNode, updater: _updateModelAccessor.ModelUpdater, isNew: false);
+            var editor = await _displayManager.UpdateEditorAsync(treeNode, updater: _updateModelAccessor.ModelUpdater, isNew: false, "", "");
```
Comment (MikeAlhayek) [inline src/OrchardCore.Modules/OrchardCore.AdminMenu/Controllers/NodeController.cs:223]: Can you please use `String.Empty` instead of `""` in all these calls?

Comment (MikeAlhayek) [reply src/OrchardCore.Modules/OrchardCore.AdminMenu/Controllers/NodeController.cs:223]: 2 seconds too late :)

Comment (ns8482e) [reply src/OrchardCore.Modules/OrchardCore.AdminMenu/Controllers/NodeController.cs:223]: @ns8482e I'll fix that in dotnet format #12235
