### PR TITLE
Re-add tenant level AFT on setup

### LINKED ISSUE #11501: Unexpected behavior when "ARR affinity" cookies is disabled
### Describe the bug
I am running OC CMS by using multiple Azure services. For this app, I am using the following services
 1. Storage Account to host "dataprotection", "shell" and media files.
 2. SQL database to host the data
 3. Redis cache to distribute my caching 
 4. Azure Web Service for Containers
 5. Other services that may not be relative to this problem like Azure Registry...

My app is running using 3 instances of the web services. so when a user makes a request to the website there are 3 different instances that could potentially handle the request. I am testing out the app scalability and would like to disable the [ARR Affinity cookie](https://azure.github.io/AppService/2016/05/16/Disable-Session-affinity-cookie-(ARR-cookie)-for-Azure-web-apps.html). When the ARR cookie is disabled, the app seems to not work as expected. It's like the app can't handle the "form post request which is a second request a user would make to submit a web form".

### To Reproduce
1. Add the following services to the host project
```
services.AddOrchardCms()
        .AddAzureShellsConfiguration()
        .AddGlobalFeatures("OrchardCore.DataProtection.Azure");
        .AddSetupFeatures("OrchardCore.Redis.Lock")
        .AddGlobalFeatures("OrchardCore.Redis.Cache", "OrchardCore.Redis.Lock");
```
2. Add the following settings in the configuration section in the Azure Web Service
  a.`OrchardCore__ConnectionString=ConnectionStringToAzureDatabase`
  b.`OrchardCore__DatabaseProvider=SqlConnection` 
  c.`OrchardCore__Default__State=Uninitialized`
  d.`OrchardCore__Default__TablePrefix=Default`
  e.`OrchardCore__OrchardCore_DataProtection_Azure__ConnectionString=ConnectionStringToStorageAccount`
  f.`OrchardCore__OrchardCore_DataProtection_Azure__ContainerName=dataprotection`
  g.`OrchardCore__OrchardCore_Media_Azure__BasePath=Media`
  h.`OrchardCore__OrchardCore_Media_Azure__ConnectionString=ConnectionStringToStorageAccount`
  i.`OrchardCore__OrchardCore_Media_Azure__ContainerName=media-{{ ShellSettings.Name }}`
  j.`OrchardCore__OrchardCore_Media_Azure__CreateContainer=true`
  k.`OrchardCore__OrchardCore_Redis__Configuration=ConnectiontToTheRedisDatabase,allowAdmin=true`
  l.`OrchardCore__OrchardCore_Shells_Azure__ConnectionString=ConnectionStringToStorageAccount`
  m.`OrchardCore__OrchardCore_Shells_Azure__ContainerName=hostcontainer`
6. Make sure you scale out the app service to at least 3 instances
image

7. Publish the app to azure web service using docker containers. 
8. Setup your default site using SaaS recipe. Ensure that the app is working with no know error as it should.
9. Let's attempt to reproduce the issue now by disabling the ARR Affinity cookie [as explained here](https://azure.github.io/AppService/2016/05/16/Disable-Session-affinity-cookie-(ARR-cookie)-for-Azure-web-apps.html)
10. With the ARR cookies disabled, go to the "Tenants" section of your dashboard and add 2+ new tenant. The results will be that one or more of the tenants won't be added or show up.
11. If you now enable the ARR Affinity cookie some of the tenants you added in the previous step my show up. Weird?

### Expected behavior
When the ARR Affinity cookie is disabled, everything should work the same since my app is using a single instance of the shell, data-protection and distributing my cache using Redis database.

### PR DESCRIPTION
**Pull request by jtkech**
Fixes #11501 

Before we were using fixed cookie names, and to prevent some logged errors on setup, in place of registering tenant ATF while the tenant is not initialized, we just remove a possible existing cookie, and let the host level registrations being used.

- We don't need this anymore as we now use fixed cookie names based on the settings VersionId.

- Also, only for the default tenant, when first creating the setup context the VersionId was null, this leading up to an `__orchantiforgery_` cookie name which was no more unique.

Useful to still register tenant level AFT even if the tenant is in a setup context, in a multi instances env to setup tenants we may want to use a tenant level shared data protection, as tried in #11501 from the app by using `AddSetupFeatures()`, and then on setup we also need a tenant level AFT that will use this DP.

### CODE REVIEW

File: src/OrchardCore/OrchardCore/Shell/ShellHost.cs [hunk 1]
```diff
@@ -378,6 +378,7 @@ private Task<ShellContext> CreateSetupContextAsync(ShellSettings defaultSettings
                 // Creates a default shell settings based on the configuration.
                 var shellSettings = _shellSettingsManager.CreateDefaultSettings();
                 shellSettings.Name = ShellHelper.DefaultShellName;
+                shellSettings.VersionId = IdGenerator.GenerateId();
```
Comment (Skrypt) [inline src/OrchardCore/OrchardCore/Shell/ShellHost.cs:381]: Will this generate a new Id every time I go to the setup page from, let's say, different browsers?

Comment (jtkech) [reply src/OrchardCore/OrchardCore/Shell/ShellHost.cs]: `CreateSetupContextAsync()` is only used for the Default tenant.

For all other tenants, each time we create/update settings, the settings are persisted so you will retrieve the same Id from any browser and any app app instance if the settings store is shared.

Here for the default tenant, the settings for setup are only set in memory, so you will get the same Id from any browser if you target the same app instance. The Id will change if you restart the app instance or target another one.

But it is so simple to also call here `UpdateShellSettingsAsync()` which will set once a new VersionId, as for other tenants, I did the update and tried it, now you will get the same Id from any browser and any targetted instance, also for the Default tenant.
