### PR TITLE
Fix typos

### LINKED ISSUE #14183: Hints in Background Edit settings
https://github.com/OrchardCMS/OrchardCore/blob/7d50c3efe37f22545dc0b47ed2572ac5086963c3/src/OrchardCore.Modules/OrchardCore.BackgroundTasks/Views/BackgroundTask/Edit.cshtml#L53
`Wether `=> `Whether`
May be rephrase (put the `or not` at the end)?

https://github.com/OrchardCMS/OrchardCore/blob/7d50c3efe37f22545dc0b47ed2572ac5086963c3/src/OrchardCore.Modules/OrchardCore.BackgroundTasks/Views/BackgroundTask/Edit.cshtml#L54
`This to configure endpoints and then to allow route urls generation` => `Check this ...` ?

Do we need two hints, one below the other?

@jtkech I let you fix it. 

Other English speakers can suggest changes to make the hint more understandable.

### PR DESCRIPTION
**Pull request by jtkech**
Fixes #14183

### CODE REVIEW

File: src/OrchardCore/OrchardCore.Abstractions/Shell/Extensions/ShellSettingsExtensions.cs [hunk 1]
```diff
@@ -51,15 +51,15 @@ public static class ShellSettingsExtensions
             StringComparison.OrdinalIgnoreCase);
 
     /// <summary>
-    /// Wether or not the tenant has one of the url host(s) defined by the provided string.
+    /// Whether or not the tenant has one of the url host(s) defined by the provided string.
```
Comment (hishamco) [inline src/OrchardCore/OrchardCore.Abstractions/Shell/Extensions/ShellSettingsExtensions.cs:54]: Copy paste everywhere :)

**Review by hishamco — APPROVED** [review]

File: src/OrchardCore/OrchardCore.Abstractions/Shell/Extensions/ShellSettingsExtensions.cs (hunk 1 above)
Comment (jtkech) [reply src/OrchardCore/OrchardCore.Abstractions/Shell/Extensions/ShellSettingsExtensions.cs:54]: Yes ;)
