### PR TITLE
Fixes FileSystemStore issues #6272

### LINKED ISSUE #6272: FileSystemStore issues
When getting file system info a relative path is passed to the FileSystemStoreEntry. 
```csharp
        public Task<IFileStoreEntry> GetFileInfoAsync(string path)
        {
            var physicalPath = GetPhysicalPath(path);
            var fileInfo = new PhysicalFileInfo(new FileInfo(physicalPath));

            if (fileInfo.Exists)
            {
                return Task.FromResult<IFileStoreEntry>(new FileSystemStoreEntry(path, fileInfo));
            }

            return Task.FromResult<IFileStoreEntry>(null);
        }
```
When calling 
```csharp
        public Task<Stream> GetFileStreamAsync(IFileStoreEntry fileStoreEntry)
        {
            if (!File.Exists(fileStoreEntry.Path))
            {
                throw new FileStoreException($"Cannot get file stream because the file '{fileStoreEntry.Path}' does not exist.");
            }

            var stream = File.OpenRead(fileStoreEntry.Path);

            return Task.FromResult<Stream>(stream);
        }
```
File operations are made with relative path. I think path must be converted to physical one or in FileStoreEntry ctor a physical one should be passed.

### PR DESCRIPTION
**Pull request by vesko-k**
Fixes #6272

### CODE REVIEW

File: src/OrchardCore/OrchardCore.FileStorage.FileSystem/FileSystemStore.cs [hunk 1]
```diff
@@ -186,12 +186,14 @@ public Task<Stream> GetFileStreamAsync(string path)
 
         public Task<Stream> GetFileStreamAsync(IFileStoreEntry fileStoreEntry)
         {
-            if (!File.Exists(fileStoreEntry.Path))
+            var physicalPath = GetPhysicalPath(fileStoreEntry.Path);
+
```
Comment (hishamco) [inline src/OrchardCore/OrchardCore.FileStorage.FileSystem/FileSystemStore.cs:190]: Just remove an extra line
