### PR TITLE
Fix Minor security issue: Internal File Path Disclosure

### LINKED ISSUE #9379: Minor security issue: Internal File Path Disclosure
Hello,

A customer of ours has had a pen test undertaken of a system we have built for them, one of the issues that has been raised is the Media module can potentially expose internal file paths, letting a would be attacker find out what OS the server is using and gaining them knowledge about the file structure being used by the web application.

image

I've tracked it down to this catch statement:

https://github.com/OrchardCMS/OrchardCore/blob/9d4fb5372e6ac0deb9d749dc746a022c3dbe46a4/src/OrchardCore.Modules/OrchardCore.Media/Controllers/AdminController.cs#L184-L195

It's down as a low priority issue on the pen test but I thought I should log it here so it can be eventually resolved. Part of me is tempted to say have a blanket default error message and if someone is really interested they can check the server logs for the full details.

### PR DESCRIPTION
**Pull request by Skrypt**
Fixes #9379

### CODE REVIEW

File: src/OrchardCore/OrchardCore.FileStorage.AzureBlob/BlobFileStore.cs [hunk 1]
```diff
@@ -61,43 +60,65 @@ public BlobFileStore(BlobStorageOptions options, IClock clock, IContentTypeProvi
...
 
-            var properties = await blob.GetPropertiesAsync();
+                var properties = await blob.GetPropertiesAsync();
 
-            return new BlobFile(path, properties.Value.ContentLength, properties.Value.LastModified);
+                return new BlobFile(path, properties.Value.ContentLength, properties.Value.LastModified);
+            }
+            catch
+            {
+                throw new FileStoreException($"Cannot get file info with path '{path}'.");
```
Comment (deanmarcussen) [inline src/OrchardCore/OrchardCore.FileStorage.AzureBlob/BlobFileStore.cs:78]:
```
catch (Exception ex)
{
    throw new FileStoreException($"Cannot get file info with path '{path}'.", ex);
}
```

File: src/OrchardCore/OrchardCore.FileStorage.AzureBlob/BlobFileStore.cs [hunk 2]
```diff
@@ -180,106 +201,147 @@ public async Task<bool> TryCreateDirectoryAsync(string path)
...
 
-            if (!await blob.ExistsAsync())
+                if (!await blob.ExistsAsync())
+                {
+                    throw new FileStoreException($"Cannot get file stream because the file '{path}' does not exist.");
+                }
+
+                return (await blob.DownloadAsync()).Value.Content;
+            }
+            catch
```
Comment (deanmarcussen) [inline src/OrchardCore/OrchardCore.FileStorage.AzureBlob/BlobFileStore.cs:341]: catch (FileStoreException)
{
    throw;
}
catch (Exception ex)
{
    throw new FileStoreException($"Cannot get file info with path '{path}'.", ex);
}

**Review by deanmarcussen — COMMENTED** [review]
Great.

What I would suggest is on the methods where we don't internally throw a `FileStoreException` already, is that we catch the unknown exception, and add it to the `FileStoreException` as the `InnerException`

This way we keep the stack trace, for the logs, but the media app / controllers won't be reading the `InnerException`

On the ones where we are throwing a `FileStoreException`, for known errors, we can catch that as `catch (FileStoreException)` and directly rethrow it with `throw;`, and then we have that known message, and no break in the strack trace.
And still catch the general exceptions and rethrow them.

Hopefully makes sense

**Review by deanmarcussen — APPROVED** [review]
