### PR TITLE
Fix non-debug version loaded for certain static resources when debug mode is enabled

### LINKED ISSUE #16401: The non-debug versions of certain static resources aren't loaded when Resource Debug Mode is set to Enabled
### Orchard Core version

4aeaaf9abe516e73662fb8993400617fc8ad087e

### To Reproduce

1. Set up a site with the Blog recipe.
2. Go to Configuration -> Settings -> General (by default https://localhost:44300/blog/Admin/Settings/general), and change Resource Debug Mode to Enabled (but "From environment", which sets the same when running locally, reproduces the same issue).
3. Open the Article editor, by default under https://localhost:44300/Admin/Contents/ContentItems/4xg73tbftb4x8r31680zxesexv/Edit This is just an example, other pages are surely also affected.
4. Notice how a lot of .min static resources are loaded, e.g. `/TheAdmin/css/admin-layout.min.css`, `/OrchardCore.Resources/Scripts/jquery.min.js`, and `/OrchardCore.Resources/Scripts/trumbowyg/trumbowyg.min.js`, despite all of these having non-minified debug versions configured. Not all resources are affected though, e.g. `/OrchardCore.Html/Scripts/trumbowyg.media.tag.js` and `/OrchardCore.Resources/Scripts/trumbowyg/trumbowyg.shortcodes.js` are correctly loaded as the debug versions.
5. Change Resource Debug Mode to Disabled, reload the Article editor, and observe how correctly only minified resources are loaded.

### Expected behavior

With Resource Debug Mode set to Enabled only the non-minified resources are loaded.

### Logs and screenshots
Foot scripts with Resource Debug Mode enabled:

image

And disabled:

image

Head scripts and stylesheets enabled:

image

Disabled:

image

Notice how the affected foot scripts seem to all lack the cache-busting `v` query string parameter as well when Resource Debug Mode is set to Enabled, which is another, most possibly related issue. This is not so clearly the case for the head resources though.

### PR DESCRIPTION
**Pull request by mdameer**
Fix #16401 

This fix addresses an issue where `ResourceManagementOptions` were not inherited by dependent resources. As a result, dependencies were always loaded in their minified versions without versioning. The following images illustrate the changes:

Before:

image

After:

image

### CODE REVIEW

File: src/OrchardCore/OrchardCore.ResourceManagement.Abstractions/RequireSettings.cs [hunk 1]
```diff
@@ -36,6 +38,8 @@ public RequireSettings()
 
         public RequireSettings(ResourceManagementOptions options)
         {
+            _options = options;
+
```
Comment (hishamco) [inline src/OrchardCore/OrchardCore.ResourceManagement.Abstractions/RequireSettings.cs:42]:
```suggestion
```

File: src/OrchardCore/OrchardCore.ResourceManagement.Abstractions/RequireSettings.cs [hunk 2]
```diff
@@ -258,14 +262,17 @@ public RequireSettings CombinePosition(RequireSettings dependent)
...
-            {
-                Name = Name,
-                Type = Type,
-                Location = Location,
-                Position = Position
-            };
+        public RequireSettings New()
+        {
+            RequireSettings settings = _options != null ? new(_options) : new();
+
```
Comment (hishamco) [inline src/OrchardCore/OrchardCore.ResourceManagement.Abstractions/RequireSettings.cs:268]:
```suggestion
            RequireSettings settings = _options != null
                ? new(_options)
                : new();
```

**Review by hishamco — CHANGES_REQUESTED** [review]

**Review by hishamco — APPROVED** [review]

**Review by Piedone — APPROVED** [review]
Thanks for the quick fix!
