### PR TITLE
Fixes multiple tenant shells initialization.

### LINKED ISSUE #2977: Tennant gone missing intermittently when deployed on Azure Web App
Background:
1. I have 2 sites in Azure. The first, site A, is on dev v1.0.0.0-betaB-69950 (rough guess). Site A has 3 tenants with custom domains and running with no issues.
2. The second site, site B, is on dev v1.0.0-beta3-70374. I was in the process of migrating the tenants on Site A to site B when saw the issues outlined below under the Error section.
3. Site A is still working with no issues. I had to put the tenants back to site A since site B had issues.
4. Please look at the Scenario section below go know what OC is running on Azure.

Error:
1. The tenants on OC started to get missing when 2nd through 4th tenant were added.
2. The first tenant was working fine, even after adding a custom domain.
3. Adding the 2nd through 4th tenants was still ok.
4. Adding the custom domain on the 2nd through 4th tenants seems to trigger the issue.( May or may not be true).
5. Error code from the log
2019-01-05 18:47:06.7974|None|0HLJJ7OO04QNO:00000001||OrchardCore.Environment.Shell.ShellHost|ERROR|A tenant could not be started 't4basicstostart' System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'IServiceProvider'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ThrowHelper.ThrowObjectDisposedException()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at OrchardCore.Mvc.ShellViewFeatureProvider..ctor(IHttpContextAccessor httpContextAccessor) in C:\dev\oc\repos\busyaprons\src\OrchardCore\OrchardCore.Mvc.Core\ShellViewFeatureProvider.cs:line 27
   at OrchardCore.Mvc.Startup.AddModularFrameworkParts(IServiceProvider services, ApplicationPartManager manager) in C:\dev\oc\repos\busyaprons\src\OrchardCore\OrchardCore.Mvc.Core\Startup.cs:line 69
   at OrchardCore.Mvc.Startup.ConfigureServices(IServiceCollection services) in C:\dev\oc\repos\busyaprons\src\OrchardCore\OrchardCore.Mvc.Core\Startup.cs:line 50
   at OrchardCore.Environment.Shell.Builders.ShellContainerFactory.CreateContainer(ShellSettings settings, ShellBlueprint blueprint) in C:\dev\oc\repos\busyaprons\src\OrchardCore\OrchardCore\Environment\Shell\Builders\ShellContainerFactory.cs:line 96
   at OrchardCore.Environment.Shell.Builders.ShellContextFactory.CreateDescribedContextAsync(ShellSettings settings, ShellDescriptor shellDescriptor) in C:\dev\oc\repos\busyaprons\src\OrchardCore\OrchardCore\Environment\Shell\Builders\ShellContextFactory.cs:line 75
   at OrchardCore.Environment.Shell.Builders.ShellContextFactory.OrchardCore.Environment.Shell.Builders.IShellContextFactory.CreateShellContextAsync(ShellSettings settings) in C:\dev\oc\repos\busyaprons\src\OrchardCore\OrchardCore\Environment\Shell\Builders\ShellContextFactory.cs:line 49
   at OrchardCore.Environment.Shell.ShellHost.GetOrCreateShellContextAsync(ShellSettings settings) in C:\dev\oc\repos\busyaprons\src\OrchardCore\OrchardCore\Environment\Shell\ShellHost.cs:line 89
   at OrchardCore.Environment.Shell.ShellHost.<CreateAndRegisterShellsAsync>b__15_0(ShellSettings settings) in C:\dev\oc\repos\busyaprons\src\OrchardCore\OrchardCore\Environment\Shell\ShellHost.cs:line 184    at Microsoft.Extensions.DependencyInjection.ServiceLookup.ThrowHelper.ThrowObjectDisposedException()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at OrchardCore.Mvc.ShellViewFeatureProvider..ctor(IHttpContextAccessor httpContextAccessor) in C:\dev\oc\repos\busyaprons\src\OrchardCore\OrchardCore.Mvc.Core\ShellViewFeatureProvider.cs:line 27
   at OrchardCore.Mvc.Startup.AddModularFrameworkParts(IServiceProvider services, ApplicationPartManager manager) in C:\dev\oc\repos\busyaprons\src\OrchardCore\OrchardCore.Mvc.Core\Startup.cs:line 69
   at OrchardCore.Mvc.Startup.ConfigureServices(IServiceCollection services) in C:\dev\oc\repos\busyaprons\src\OrchardCore\OrchardCore.Mvc.Core\Startup.cs:line 50
   at OrchardCore.Environment.Shell.Builders.ShellContainerFactory.CreateContainer(ShellSettings settings, ShellBlueprint blueprint) in C:\dev\oc\repos\busyaprons\src\OrchardCore\OrchardCore\Environment\Shell\Builders\ShellContainerFactory.cs:line 96
   at OrchardCore.Environment.Shell.Builders.ShellContextFactory.CreateDescribedContextAsync(ShellSettings settings, ShellDescriptor shellDescriptor) in C:\dev\oc\repos\busyaprons\src\OrchardCore\OrchardCore\Environment\Shell\Builders\ShellContextFactory.cs:line 75
   at OrchardCore.Environment.Shell.Builders.ShellContextFactory.OrchardCore.Environment.Shell.Builders.IShellContextFactory.CreateShellContextAsync(ShellSettings settings) in C:\dev\oc\repos\busyaprons\src\OrchardCore\OrchardCore\Environment\Shell\Builders\ShellContextFactory.cs:line 49
   at OrchardCore.Environment.Shell.ShellHost.GetOrCreateShellContextAsync(ShellSettings settings) in C:\dev\oc\repos\busyaprons\src\OrchardCore\OrchardCore\Environment\Shell\ShellHost.cs:line 89
   at OrchardCore.Environment.Shell.ShellHost.<CreateAndRegisterShellsAsync>b__15_0(ShellSettings settings) in C:\dev\oc\repos\busyaprons\src\OrchardCore\OrchardCore\Environment\Shell\ShellHost.cs:line 184

Scenario
1. Deployed on Azure
2. Location: Central US
3. App Service Plan: Both on D1 and B1 pricing tiers
4. SQL Server - Azure SQL Database

### PR DESCRIPTION
**Pull request by jtkech**
Fixes #2977.

I could repro the issue by creating multiple tenants on my machine.

- When entering in our custom shell scope we swap the existing `RequestServices` with our scoped service provider until the end of the scope. The problem is when using `Task.WhenAll` to 1st initialize all tenants where, even if no full parallelism, the flow of each individual task progresses in "parallel".

    In this context, a tenant scope may cache and then return to the `RequestServices` the service provider of another tenant scope that will be disposed. It fails in the new `ShellViewFeatureProvider` where we use `RequestServices` to resolve application singletons. An easy fix is to resolve them later, i tried it. But i think that this issue just highlighted another problem that we need to fix in another way.

- I had this kind of issues in background tasks, the other place where we create multiple shells, here with full parallelism. We needed to isolate the `HttpContext`, now naturally done in a host service, and in each task we needed to create a new isolated `HttpContext`. But here maybe better to find a simpler way.

- But but but, when we 1st compose all shells (i don't talk about building the pipeline) the only place where we use our custom scope is in `ShellContextFactory`, just to resolve `IShellDescriptorManager`. This is here that i saw the interleaving of scopes creation / disposing and the mixing of services. **So, replacing `describedContext.CreateScope()` with `describedContext.ServiceProvider.CreateScope()` to use a regular `IServiceScope` also fixed the issue**.

- For infos, i also saw that `ShellContextFactory` resolves `IShellDescriptorManager` => `ISession` => we add this session in `httpContext.Items` which is not concurrent. I had this issue when creating shells with full parallelism but not isolated httpContext. But with `Task.WhenAll` where tasks are not triggered e.g by task run, as i checked non async codes between 2 await are not fully run in parallel so seems to be ok.

    So, on the 1st tenants init, the result is just that the last initialized tenant wins to put its session in `httpContext.Items`, but afterwards we create a new scope on the right tenant to really serve the request, so seems to be ok. I tried it by starting with an url to edit directly an item of a given tenant.

### CODE REVIEW

File: src/OrchardCore/OrchardCore/Environment/Shell/ShellHost.cs [hunk 1]
```diff
@@ -177,11 +177,11 @@ async Task CreateAndRegisterShellsAsync()
             else
             {
                 // Load all tenants, and activate their shell.
-                await Task.WhenAll(allSettings.Select(async settings =>
+                await Task.WhenAll(allSettings.Select(settings =>
                 {
                     try
                     {
-                        await GetOrCreateShellContextAsync(settings);
+                        return GetOrCreateShellContextAsync(settings);
```
Comment (PinpointTownes) [inline src/OrchardCore/OrchardCore/Environment/Shell/ShellHost.cs]: Hum, I'm tempted to think this will just hide the problem, as this code path will no longer catch "async exceptions" (e.g exceptions thrown after an `await` or using `Task.FromException`).

Comment (sebastienros) [reply src/OrchardCore/OrchardCore/Environment/Shell/ShellHost.cs]: I agree. I am reverting the change.

Comment (sebastienros) [reply src/OrchardCore/OrchardCore/Environment/Shell/ShellHost.cs]: Done. Please ensure this was not related to the issue this PR is fixing.

**Comment by PinpointTownes** [comment]
I've already said it, but I'm still 100% convinced it's awkward to do things like storing the `ISession` in the `HttpContext`, creating a fake `HttpContext` when there's really no request context (e.g background tasks) or even using `IHttpContextAccessor` in a primitive like `ShellContext`. All of that combined is a disaster waiting to happen :cry:

**Comment by sebastienros** [comment]
Can you file an issue (you might have already). We need to introduce new interfaces as we see usages of `IHCA` when not requiring an actual request, and remove the `ISession` from context items as it's already in DI.

File: src/OrchardCore/OrchardCore/Environment/Shell/ShellHost.cs (hunk 1 above)
Comment (jtkech) [reply src/OrchardCore/OrchardCore/Environment/Shell/ShellHost.cs]: The issue was fixed without this change that i did at the end, so no problem to revert it.
Sorry, i didn't see that it avoids to catch some exceptions.

**Comment by jtkech** [comment]
Yes, maybe great to limit the usage of IHCA and there maybe many places where we could get rid of it. But i don't totally agree that each time there is an issue related to IHCA we have to blame it.

It's like we don't want to use a simple dictionary just because it doesn't support concurrent writes.

here the issue just reminded us that for a given http context we can only create scopes in a normal flow (at least for now) without interleaving scopes creations / disposings. Otherwise we have to do some isolations.

So, i think that IHCA is as it is and it has the advantage to hold an AsyncLocal value which is set at the very beginning of a request, which can be very useful.

But i agree that e.g services which have nothing related to a request should not use IHCA. And very interesting to think about another way to deal with contextual service providers and so on.

But maybe sometimes we have to do "weird" things as in bg tasks so that people don't have to think about the context. Maybe sometimes we have no choice but to adapt to the context provided by aspnetcore, but you will say that we have not to depend on aspnetcore ;)

Just as an example, we worked recently on a way to display shapes without any ViewContext so that people can write templates without thinking about this. We didn't find another way than to create a fake ViewContext.

Here just an example where we use httpContext items to not use the DI.

            // Don't resolve to prevent instantiating one in case of static sites
            var session = httpContext.Items[typeof(YesSql.ISession)] as YesSql.ISession;

**Comment by PinpointTownes** [comment]
> But maybe sometimes we have to do "weird" things as in bg tasks so that people don't have to think about the context.

Don't you think it would be better to be hyper explicit and tell folks that no ASP.NET Core context is available from BG tasks? I don't think creating a fake context - that can't be used for anything "real world", as none of the traditional properties (host, path, features, etc.) are there - is a good idea. It's not even consistent with how hosted services in ASP.NET Core work.

> Maybe sometimes we have no choice but to adapt to the context provided by aspnetcore, but you will say that we have not to depend on aspnetcore ;)

Personally, that's certainly how I'd design it, yes: it would be much clearer and cleaner if the core components of OC - mostly the shell system - didn't depend on anything from `Microsoft.AspNetCore.*` and if the pipeline stuff was part of a separate `OrchardCore.AspNetCore` package.

If one day someone wants to use OC for a local management console, he or she will have a really bad surprise :sweat_smile:

**Comment by PinpointTownes** [comment]
@sebastienros done: https://github.com/OrchardCMS/OrchardCore/issues/2993

**Comment by sebastienros** [comment]
Forgive me if this was already mentioned. Something very common in background tasks is generate emails from templates. These will render urls, and require Url Helper, which requires a Request. Just an example why we might need a fake HttpRequest in a BG task.

How would you solve it? I could see a custom `IHostNameProvider` if we just need a root for the urls that we generate. Can we render urls to mvc actions still?

**Comment by jtkech** [comment]
@PinpointTownes thanks for the explanation, i've the feeling that at the end you will be right, but i like to understand things ;)

@sebastienros maybe in this case this is the responsability of some services (not core components) with specific methods to do this by creating fake contexts, as we did recently to render a shape without view context. And to create this viewContext we were using `httpContextAccessor.HttpContext` ;)

**Comment by PinpointTownes** [comment]
> How would you solve it?

What you proposed is fine: a custom `UrlHelper` that takes an `ActionContext` specially crafted for the template engine to work (which is what the BG service does, but without having to use `IHttpContextAccessor`).

My point is that this should never be done in OC's core components themselves, specially the background service. If specific tasks *absolutely* require an ASP.NET Core context, then it should be handled locally (without IHCA) and not globally :grinning:

**Comment by PinpointTownes** [comment]
> How would you solve it? I could see a custom IHostNameProvider if we just need a root for the urls that we generate. Can we render urls to mvc actions still?

It's worth noting that even the fake request approach is not without downsides, as it will only work with tenants that specify an explicit host (and not just a path base). If they don't, you'll end up with a `localhost` host, that will of course never work to generate a link for an email.
