### PR TITLE
Preload site settings on tenant activation

### LINKED ISSUE #17547: Orchard Core can cause dependency resolution problems due to use of async code in non-async context
### Describe the bug
I've been experiencing request timeouts caused by what seemed to be dependency injection problems but turned out to be a result of executing async code within OrcardCore as synchronous. Specifically, in OrchardCore.DynamicCache.CacheOptionsConfiguration.Configure:
```c#
        switch (_siteService.GetSiteSettingsAsync().GetAwaiter().GetResult()
            .CacheMode)
        {
             // ... other code
        }
```
This is resulting in blocking when resolving types like IContentManager.

I originally posted this in the OrchardCore discord but was advised to raise this issue on Github.

### Orchard Core version

2.1.6

### To Reproduce

I don't have isolated code to reproduce it but this is a blazor server app and I have a service registered with ```AddScoped``` that has ```IContentManager``` and ```ISession``` as dependencies. This issue doesn't happen 100% of the time but it happens fairly often, especially on the first request to the hosting page after startup.

### Expected behavior

```IContentManager``` and ```ISession``` should be resolved consistently without blocking. 

### Logs and screenshots

Debugging in Visual studio with Just-my-code disabled revealed the following:

Image

The origin is this line here:

Image

### PR DESCRIPTION
**Pull request by gvkries**
This PR addresses potential issues caused by retrieving site settings in a synchronous-over-asynchronous manner. By preloading the site settings when a tenant is activated, we can mitigate these problems. The preloading process is asynchronous, and since the site settings are cached in-memory, subsequent access remains non-blocking.

Additionally, when site settings are updated, they are immediately reloaded into the cache to ensure consistency.

To handle the unavoidable synchronous retrieval of site settings in Configure() callbacks, I have introduced a synchronous extension method for `ISiteService` to emphasize it is safe to call them synchronously. The most common call sites have been updated accordingly.

Fixes #17547

### CODE REVIEW

File: src/OrchardCore/OrchardCore.Infrastructure.Abstractions/Settings/SiteServiceExtensions.cs [hunk 1]
```diff
@@ -22,4 +22,19 @@ public static class SiteServiceExtensions
     /// <returns>An instance of the given type if one exists.</returns>
     public static async Task<T> GetSettingsAsync<T>(this ISiteService siteService, string name) where T : new()
         => (await siteService.GetSiteSettingsAsync()).As<T>(name);
+
+    /// <summary>
+    /// Gets the site settings from the cache.
+    /// </summary>
+    public static ISite GetSiteSettings(this ISiteService siteService)
```
Comment (MikeAlhayek) [inline src/OrchardCore/OrchardCore.Infrastructure.Abstractions/Settings/SiteServiceExtensions.cs:29]: I don't think this is a good extension.

File: src/OrchardCore/OrchardCore.Infrastructure.Abstractions/Settings/SiteServiceExtensions.cs [hunk 2]
```diff
@@ -22,4 +22,19 @@ public static class SiteServiceExtensions
...
+        => siteService.GetSiteSettingsAsync().GetAwaiter().GetResult();
+
+    /// <summary>
+    /// Gets an instance of the specified settings if it exists.
+    /// </summary>
+    /// <typeparam name="T">The type of the settings to attempt to get.</typeparam>
+    /// <param name="siteService">The site service.</param>
+    /// <returns>An instance of the given type if one exists.</returns>
+    public static T GetSettings<T>(this ISiteService siteService) where T : new()
```
Comment (MikeAlhayek) [inline src/OrchardCore/OrchardCore.Infrastructure.Abstractions/Settings/SiteServiceExtensions.cs:38]: I think we had extension like this that was removed I believe.

File: src/OrchardCore.Modules/OrchardCore.Settings/Services/TenantEventHandler.cs [hunk 3]
```diff
@@ -0,0 +1,29 @@
+using OrchardCore.Environment.Shell;
+using OrchardCore.Modules;
+
+namespace OrchardCore.Settings.Services;
+
+internal sealed class TenantEventHandler : ModularTenantEvents
```
Comment (MikeAlhayek) [inline src/OrchardCore.Modules/OrchardCore.Settings/Services/TenantEventHandler.cs:6]: I think this is the only think that is needed here to fix the issue. The rest of the changes should not be needed.

File: src/OrchardCore.Modules/OrchardCore.Settings/Services/SiteService.cs [hunk 4]
```diff
@@ -41,7 +41,7 @@ public async Task UpdateSiteSettingsAsync(ISite site)
             return;
         }
 
-        await _documentManager.UpdateAsync(siteSettings);
+        await _documentManager.UpdateAsync(siteSettings, _ => GetSiteSettingsAsync());
```
Comment (MikeAlhayek) [inline src/OrchardCore.Modules/OrchardCore.Settings/Services/SiteService.cs:44]: Maybe this is part of the fix too.

File: src/OrchardCore/OrchardCore.Infrastructure.Abstractions/Settings/SiteServiceExtensions.cs (hunk 2 above)
Comment (gvkries) [reply src/OrchardCore/OrchardCore.Infrastructure.Abstractions/Settings/SiteServiceExtensions.cs:38]: I don't see anything related to `ISiteService`, this has always been asynchronous. And the extension methods were added last year by yourself.

File: src/OrchardCore/OrchardCore.Infrastructure.Abstractions/Settings/SiteServiceExtensions.cs (hunk 1 above)
Comment (gvkries) [reply src/OrchardCore/OrchardCore.Infrastructure.Abstractions/Settings/SiteServiceExtensions.cs:29]: I understand your concerns about the extension method. However, I believe it is beneficial to include this in OrchardCore for the following reasons:

- `IOptions` are inherently synchronous, meaning any configuration callback using site settings will require synchronous access. This is unlikely to change. By providing a synchronous extension method, we align with this design principle and avoid the pitfalls of sync-over-async patterns.
- Using `GetAwaiter().GetResult()` can be confusing and misleading. It suggests that asynchronous operations are being forced into synchronous contexts, which is generally considered a bad practice. By encapsulating this synchronous retrieval within our extension method, we provide a cleaner and more intuitive API for developers.
- Formalizing the synchronous retrieval of site settings through our extension method ensures consistency across the codebase. Module and theme authors can rely on a standardized approach, reducing the likelihood of errors and misunderstandings.
- Hiding the complexity of synchronous retrieval within our extension method improves the developer experience. It allows developers to focus on their core tasks without worrying about the intricacies of sync-over-async issues.
- The extension method enhances code readability.

I hope these points help clarify the benefits of the extension method.

Comment (MikeAlhayek) [reply src/OrchardCore/OrchardCore.Infrastructure.Abstractions/Settings/SiteServiceExtensions.cs:29]: > Using GetAwaiter().GetResult() can be confusing and misleading. 

I think it is more confusing to wrap a non-async method with this `siteService.GetSiteSettingsAsync().GetAwaiter().GetResult();` I rather see use using `.GetAwaiter().GetResult()` in the configuration files that wrapping that with this extension since it hides too much in this case.

File: src/OrchardCore/OrchardCore.Infrastructure.Abstractions/Settings/SiteServiceExtensions.cs (hunk 2 above)
Comment (MikeAlhayek) [reply src/OrchardCore/OrchardCore.Infrastructure.Abstractions/Settings/SiteServiceExtensions.cs:38]: I think we had one at some point and we removed it so we can use async.

File: src/OrchardCore/OrchardCore.Infrastructure.Abstractions/Settings/SiteServiceExtensions.cs (hunk 1 above)
Comment (gvkries) [reply src/OrchardCore/OrchardCore.Infrastructure.Abstractions/Settings/SiteServiceExtensions.cs:29]: It tells module developers that using this synchronously is possible, without the usual problems that comes with sync-over-async. It's not about hiding something, it's formalizing a totally valid use case as we don't have any other possibility. Why should we sprinkle the code with duplicated `GetAwaiter().GetResult()` calls all over the place, which causes anyone seeing it to question it every time one has to write it.

Comment (gvkries) [reply src/OrchardCore/OrchardCore.Infrastructure.Abstractions/Settings/SiteServiceExtensions.cs:29]: That's like in every other case where there are synchronous and asynchronous methods. And yes, this info is hidden from them because we have thought that through. Why should everyone else do this work over and over again.
Anyway, I've given my opinion. Maybe let's get feedback from others as well.

Comment (MikeAlhayek) [reply src/OrchardCore/OrchardCore.Infrastructure.Abstractions/Settings/SiteServiceExtensions.cs:29]: Yes. Good PR to review today during meeting

**Comment by gvkries** [comment]
I adjusted the synchronous method a little bit, as requested by @sebastienros. But I don't see a big advantage of doing that, it's maybe one very small stack allocation less.
Also, I'm not sure if we should add this to the 'ISiteService` interface. I'll rather leave it as an extension method to allow us to change it back, in case I'm mistaken.

File: src/OrchardCore.Modules/OrchardCore.Settings/Services/TenantEventHandler.cs (hunk 3 above)
Comment (sebastienros) [inline src/OrchardCore.Modules/OrchardCore.Settings/Services/TenantEventHandler.cs:6]: Rename with something containing `SiteSettings` or `Preload`/`EagerLoad` or both.

File: src/OrchardCore/OrchardCore.Infrastructure.Abstractions/Settings/SiteServiceExtensions.cs [hunk 5]
```diff
@@ -22,4 +22,23 @@ public static class SiteServiceExtensions
     /// <returns>An instance of the given type if one exists.</returns>
     public static async Task<T> GetSettingsAsync<T>(this ISiteService siteService, string name) where T : new()
         => (await siteService.GetSiteSettingsAsync()).As<T>(name);
+
+    /// <summary>
+    /// Gets the site settings from the cache.
+    /// </summary>
+    public static ISite GetSiteSettings(this ISiteService siteService)
```
Comment (sebastienros) [inline src/OrchardCore/OrchardCore.Infrastructure.Abstractions/Settings/SiteServiceExtensions.cs:29]: Add/complete with a comment mentioning it's using the event handler to eagerly load the settings such that reading the settings synchronously is fine here. 
Also add a docs comment, more visible, that users should only use it in places that are not async, or they should use the other method.

Same for the `<TSettings>` version below.

File: src/OrchardCore.Modules/OrchardCore.Settings/Services/TenantEventHandler.cs (hunk 3 above)
Comment (gvkries) [reply src/OrchardCore.Modules/OrchardCore.Settings/Services/TenantEventHandler.cs]: Done.
