### PR TITLE
Prevents an antiforgery issue on setup.

### LINKED ISSUE #3293: AntiforgeryValidationException on setup screen
1. Open the freshly cloned solution in VS.
2. Run via IIS Express with Ctrl + F5.
3. Once the setup screen loads the following exception will be logged:

> 2019-03-07 21:46:19.1911|Default|80000020-0003-ff00-b63f-84710c7967bb||Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgery|ERROR|An exception was thrown while deserializing the token. Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: The antiforgery token could not be decrypted. ---> System.Security.Cryptography.CryptographicException: The key {d5291043-225b-445d-96a0-5f37ab41318c} was not found in the key ring.
>    at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
>    at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.DangerousUnprotect(Byte[] protectedData, Boolean ignoreRevocationErrors, Boolean& requiresMigration, Boolean& wasRevoked)
>    at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
>    at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
>    --- End of inner exception stack trace ---
>    at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
>    at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgery.GetCookieTokenDoesNotThrow(HttpContext httpContext)    at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
>    at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgery.GetCookieTokenDoesNotThrow(HttpContext httpContext)

If you start the app again then this won't happen, but you can get it again if you delete the App_Data folder.

Since this exception is swalloed and doesn't cause the setup to fail (you can set up the site without issues) it's not a huge deal. Nertheless not ideal.

Latest dev (eda45527dbc077b40932fe7cdbe37df204013465). CC @barthamark

### PR DESCRIPTION
**Pull request by jtkech**
Another way to try to fix #3293

### CODE REVIEW

**Comment by jtkech** [comment]
As a reminder.

So, here i add again the intermittent issue of the GraphQL `ShouldListBlogPostWhenCallingAQuery` unit test. The unit test fails on a count issue, not an order issue. The exception throwed during this test is a Lucene `LockObtainFailedException: Lock obtain timed out`. When i will have time i will investigate more.

Just saw that the `LOCK_POLL_INTERVAL` = 1000 ms, but also the default `WRITE_LOCK_TIMEOUT`, so we only try once to obtain the lock. Maybe we could try to increase the `WriteLockTimeout` property of the `IndexWriterConfig`.

**Comment by carlwoodhouse** [comment]
will be nice to not see that error when doing dev ;)

File: src/OrchardCore/OrchardCore/Modules/Extensions/ServiceCollectionExtensions.cs [hunk 1]
```diff
@@ -166,13 +168,21 @@ private static void AddAntiForgery(OrchardCoreBuilder builder)
             {
                 var settings = serviceProvider.GetRequiredService<ShellSettings>();
 
-                var tenantName = settings.Name;
+                var cookieName = "orchantiforgery_" + settings.Name;
```
Comment (sebastienros) [inline src/OrchardCore/OrchardCore/Modules/Extensions/ServiceCollectionExtensions.cs]: I assume that otherwise the name of the cookie in a Setup context is the same as the standard one in ASP.NET?
In this case can't we just delete two cookies? The one with the standard name, and the one for the tenant name? In the GET method of the setup?

Comment (jtkech) [reply src/OrchardCore/OrchardCore/Modules/Extensions/ServiceCollectionExtensions.cs]: Here, when the tenant is not initialized, we 1st still use the host level middleware, so setting the cookie name at the tenant level has no effect, the host middleware will still use the host level options with the standard cookie name.

So, here we set the tenant cookie name just to retrieve it on tenant setup (e.g in place of using an hard coded string) and to be able to remove an eventual previous tenant level cookie.

Comment (sebastienros) [reply src/OrchardCore/OrchardCore/Modules/Extensions/ServiceCollectionExtensions.cs]: I am suggesting to delete well-known cookies, nothing to do with configuration.

For instance, what if in the controller we would delete the cookies name `"orchantiforgery_" + settings.Name` and any starting with `.AspNetCore.Antiforgery.`

Comment (jtkech) [reply src/OrchardCore/OrchardCore/Modules/Extensions/ServiceCollectionExtensions.cs]: Ah okay, i will try it

**Comment by jtkech** [comment]
@sebastienros 

So, i did some tests, if i remove all `.AspNetCore.Antiforgery...` cookies it is the same, if i keep my updates in the startup it works, if i remove these updates there is the logging error as before.

When a cookie is already there, the issue, as seen in the log, is also related to the data protection storage which is not ready at the tenant level, but that's ok at the host level.

Note: At some point we were using only the host level antiforgery, so we were not seeing this issue.

**Comment by jtkech** [comment]
@sebastienros i found a simpler way, just one file changed.

**Comment by sebastienros** [comment]
Fixes #3293
