### PR TITLE
Obsolete ILocalClock.LocalNowAsync

### LINKED ISSUE #16751: ILocalClock.LocalNowAsync causes a VSTHRD003 code analysis warning
### Describe the bug
Calls to `ILocalClock.LocalNowAsync` [causes a VSTHRD003 code analysis warning.](https://github.com/Microsoft/vs-threading/blob/main/doc/analyzers/VSTHRD003.md)

> Avoid awaiting or returning a Task representing work that was not started within your context as that can lead to deadlocks.

### Orchard Core version
Orchard Core 1.8.2

### To Reproduce
1. Add a package reference to `Microsoft.VisualStudio.Threading.Analyzers` version 17.11.20
2. Call `ILocalClock.LocalNowAsync`

### Expected behavior
No code analysis warning is thrown.

I'm not super knowledgeable in this area but I suspect the issue is because the `LocalNowAsync` property isn't actually `async`. As far as I know async properties are not a thing in C#. Making this an `async` method would probably resolve the issue. Either that or this is a false positive, but I don't know enough to say.

The implementation of the property simply calls the private `GetLocalNowAsync` method. Presumably if that method was made public I could call it instead and avoid the warning.

### PR DESCRIPTION
**Pull request by hishamco**
Fixes #16751

I'm not sure why we added an `async` property which was the first time I saw it in my life. @rjpowers10 could you please try to reproduce in this PR

### CODE REVIEW

File: src/OrchardCore/OrchardCore.Abstractions/Modules/Services/ILocalClock.cs [hunk 1]
```diff
@@ -5,10 +5,14 @@ namespace OrchardCore.Modules;
 /// </summary>
 public interface ILocalClock
 {
+    [Obsolete("This property has been deprecated, please use GetLocalNowAsync() instead.", error: true)]
```
Comment (Piedone) [inline src/OrchardCore/OrchardCore.Abstractions/Modules/Services/ILocalClock.cs:8]:
```suggestion
    [Obsolete("This property has been deprecated and will be removed in a future version. Please use GetLocalNowAsync() instead.", error: true)]
```

Comment (MikeAlhayek) [inline src/OrchardCore/OrchardCore.Abstractions/Modules/Services/ILocalClock.cs:8]: why do we need error: true?

Also 
```suggestion
    [Obsolete("This property is deprecated and will be removed in version 3. Please use GetLocalNowAsync() as the replacement.", error: true)]
```

**Review by Piedone — CHANGES_REQUESTED** [review]

File: src/OrchardCore/OrchardCore.Abstractions/Modules/Services/ILocalClock.cs (hunk 1 above)
Comment (Piedone) [reply src/OrchardCore/OrchardCore.Abstractions/Modules/Services/ILocalClock.cs:8]: Added the same time as https://github.com/OrchardCMS/OrchardCore/pull/16752#discussion_r1765669230.

File: src/OrchardCore/OrchardCore.Abstractions/Modules/Services/ILocalClock.cs [hunk 2]
```diff
@@ -5,10 +5,14 @@ namespace OrchardCore.Modules;
...
+    Task<DateTimeOffset> LocalNowAsync => GetLocalNowAsync();
+
     /// <summary>
     /// Gets the time for the local time zone.
     /// </summary>
-    Task<DateTimeOffset> LocalNowAsync { get; }
+
+    Task<DateTimeOffset> GetLocalNowAsync();
```
Comment (MikeAlhayek) [inline src/OrchardCore/OrchardCore.Abstractions/Modules/Services/ILocalClock.cs:15]: This introduces a breaking change. To avoid having a breaking change so this instead

```
Task<DateTimeOffset> LocalNowAsync { get; }

Task<DateTimeOffset> GetLocalNowAsync()
    => LocalNowAsync ;

```

File: src/OrchardCore/OrchardCore.Abstractions/Modules/Services/ILocalClock.cs (hunk 1 above)
Comment (Piedone) [reply src/OrchardCore/OrchardCore.Abstractions/Modules/Services/ILocalClock.cs:8]: Yeah, `error` shouldn't be there, we just want a warning.

**Comment by Piedone** [comment]
`Addresses #16751` isn't understood by GitHub. Please use `Fixes #16751` or some of the other magic words to connect PRs to issues.

File: src/OrchardCore/OrchardCore.Abstractions/Modules/Services/ILocalClock.cs (hunk 2 above)
Comment (hishamco) [reply src/OrchardCore/OrchardCore.Abstractions/Modules/Services/ILocalClock.cs:15]: Why it's a breaking change? the value still comes from the new implementation, right?

Comment (Piedone) [reply src/OrchardCore/OrchardCore.Abstractions/Modules/Services/ILocalClock.cs:15]: It's for when you have an existing alternative implementation. Should be rare but can happen: Then, with Mike's code, no change is needed, only when we remove `LocalNowAsync`.

Comment (hishamco) [reply src/OrchardCore/OrchardCore.Abstractions/Modules/Services/ILocalClock.cs:15]: That's why I used error before to let the compiler complains whenever we use it

Comment (MikeAlhayek) [reply src/OrchardCore/OrchardCore.Abstractions/Modules/Services/ILocalClock.cs]: > That's why I used error before to let the compiler complains whenever we use it

this will break people. So we have to avoid it. Doing my suggestion then no breaking change because in the interface we provide the default implementation. In your implementation, you can change the default behavior found in the interface.

**Review by MikeAlhayek — APPROVED** [review]
Fixed the build

**Review by Piedone — APPROVED** [review]
