### PR TITLE
Can't Reload Stream Config Provider

### LINKED ISSUE #14496: When Database Shells Configuration Provider is used there is an exception on startup
@jtkech When [Database Shells Configuration Provider](https://docs.orchardcore.net/en/latest/docs/reference/core/Shells/#database-shells-configuration-provider) is used there is an exception on startup:

```
System.InvalidOperationException: StreamConfigurationProviders cannot be loaded more than once.
   at Microsoft.Extensions.Configuration.StreamConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationRoot.Reload()
   at OrchardCore.Environment.Shell.ShellSettingsManager.LoadSettingsAsync(String tenant)
   at OrchardCore.Environment.Shell.Distributed.DistributedShellHostedService.LoadingAsync()
   at OrchardCore.Environment.Shell.ShellHost.PreCreateAndRegisterShellsAsync()
   at OrchardCore.Environment.Shell.ShellHost.InitializeAsync()
   at OrchardCore.Modules.ModularTenantContainerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

_Originally posted by @wAsnk in https://github.com/OrchardCMS/OrchardCore/issues/14117#issuecomment-1759957496_

### PR DESCRIPTION
**Pull request by jtkech**
Fixes #14496 

Related to https://github.com/OrchardCMS/OrchardCore/issues/14117#issuecomment-1759957496

### CODE REVIEW

File: src/OrchardCore/OrchardCore/Shell/ShellSettingsManager.cs [hunk 1]
```diff
@@ -304,6 +299,15 @@ private async Task EnsureConfigurationAsync()
             _configuration = configuration;
         }
 
+        private async Task ReloadTenantsSettingsAsync()
+        {
+            using var disposable = _tenantsSettingsRoot as IDisposable;
```
Comment (sebastienros) [inline src/OrchardCore/OrchardCore/Shell/ShellSettingsManager.cs:304]: Where did you learn that from! This is C# magic

Comment (jtkech) [reply src/OrchardCore/OrchardCore/Shell/ShellSettingsManager.cs:304]: I don't remember ;) I know that `var disposable` will be disposed without failing if it is null.

**Review by sebastienros — APPROVED** [review]
