### PR TITLE
Fix get duplicate items

### LINKED ISSUE #14018: ContentManager.GetAsync(string[]) returns inconsistent results when there are duplicate ids
### Describe the bug
If the `GetAsync(string[])` is called multiple times with a string array containing duplicate content item ids, the results are inconsistent.
The first time the function is called, each content item is returned only once; even if the id is given twice.
Every call after that, duplicate content items appear if the id is passed into the function twice.

### To Reproduce
1. Call `ContentManager.GetAsync(string[])` with some string array with duplicate ids. e.g. `["ContentItemId-A", "ContentItemId-A"]`
2. Call `ContentManager.GetAsync(string[])` with the same string array with duplicate ids. (The calls can be made one after another with the same array.)
3. The first call will only return 1 result. The second call will return 2 results.

### Expected behavior
The duplicate content items are NOT returned. It should be a list with only distinct content items.

### Screenshots
image
image

### PR DESCRIPTION
**Pull request by jtkech**
Fix #14018 

We loop on each id of the passed `contentItemIds` to check if it is session cached, so if there is a duplicate id related to a cached item, we enlist this cached item twice.

So this is not an issue of the cahe, we only need to make `contentItemIds` a collection of distinct ids, which is also useful when used through the `.IsIn()` of the query predicate.

### CODE REVIEW

File: src/OrchardCore/OrchardCore.ContentManagement/DefaultContentManager.cs [hunk 1]
```diff
@@ -89,14 +89,13 @@ public Task<ContentItem> GetAsync(string contentItemId)
...
         public async Task<IEnumerable<ContentItem>> GetAsync(IEnumerable<string> contentItemIds, bool latest = false)
         {
-            if (contentItemIds == null)
-            {
-                throw new ArgumentNullException(nameof(contentItemIds));
-            }
+            contentItemIds = contentItemIds
+                ?.Where(id => id is not null)
+                .Distinct()
+                ?? throw new ArgumentNullException(nameof(contentItemIds)); ;
```
Comment (hishamco) [inline src/OrchardCore/OrchardCore.ContentManagement/DefaultContentManager.cs:95]:
```suggestion
                ?? throw new ArgumentNullException(nameof(contentItemIds)); 
```

**Review by hishamco — APPROVED** [review]
