### PR TITLE
Makes sure data migrations are assigned to a single feature only

### LINKED ISSUE #16248: Migration type identification error
```
Error while running migration version 0 for 'OrchardCore.Contents'. 
OrchardCore.Recipes.Models.RecipeExecutionException: SQLite Error 1: 'no such table: DeploymentPlanIndex'.
```

It should have something to do with #15793. 
/cc @gvkries            

https://github.com/OrchardCMS/OrchardCore/blob/0a96f448661af68789b7a46d0149f4f177386c71/src/OrchardCore/OrchardCore.Data.YesSql/Migration/DataMigrationManager.cs#L275-L285

When `OrchardCore.Contents` is passed in, it recognises its submodule's migration type as its own, e.g. `ExportContentToDeploymentTargetMigrations`, which is actually the `ExportContentToDeploymentTarget` is part of the `ExportContentToDeploymentTarget` feature.

src/OrchardCore.Modules/OrchardCore.Contents/Deployment/ExportContentToDeploymentTarget/ExportContentToDeploymentTargetMigrations.cs

_Originally posted by @hyzx86 in https://github.com/OrchardCMS/OrchardCore/issues/16212#issuecomment-2150388499_

Full Log
```
Error while running migration version 0 for 'OrchardCore.Contents'. OrchardCore.Recipes.Models.RecipeExecutionException: SQLite Error 1: 'no such table: DeploymentPlanIndex'.
 ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such table: DeploymentPlanIndex'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements()+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.GetStatements()+MoveNext()
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 434
   at YesSql.Store.<>c__DisplayClass44_0`2.<<ProduceAwaitedAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at YesSql.Data.WorkDispatcher`2.ScheduleAsync[TState](TKey key, TState state, Func`3 valueFactory)
   at YesSql.Store.ProduceAwaitedAsync[T,TState](WorkerQueryKey key, Func`3 work, TState state)
   at YesSql.Services.DefaultQuery.Query`1.ListImpl()
   at YesSql.Services.DefaultQuery.Query`1.ListImpl()
   at OrchardCore.Deployment.DeploymentPlanService.CreateOrUpdateDeploymentPlansAsync(IEnumerable`1 deploymentPlans) in D:\SourceCodes\JZSoft\EasyOC.OrchardCore\OrchardCore\src\OrchardCore.Modules\OrchardCore.Deployment\DeploymentPlanService.cs:line 97
   at OrchardCore.Recipes.Services.RecipeExecutor.<>c__DisplayClass8_0.<<ExecuteStepAsync>b__0>d.MoveNext() in D:\SourceCodes\JZSoft\EasyOC.OrchardCore\OrchardCore\src\OrchardCore\OrchardCore.Recipes.Core\Services\RecipeExecutor.cs:line 188
--- End of stack trace from previous location ---
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute, Boolean activateShell) in D:\SourceCodes\JZSoft\EasyOC.OrchardCore\OrchardCore\src\OrchardCore\OrchardCore.Abstractions\Shell\Scope\ShellScope.cs:line 275
   at OrchardCore.Recipes.Services.RecipeExecutor.ExecuteStepAsync(RecipeExecutionContext recipeStep) in D:\SourceCodes\JZSoft\EasyOC.OrchardCore\OrchardCore\src\OrchardCore\OrchardCore.Recipes.Core\Services\RecipeExecutor.cs:line 171
   at OrchardCore.Recipes.Services.RecipeExecutor.ExecuteAsync(String executionId, RecipeDescriptor recipeDescriptor, IDictionary`2 environment, CancellationToken cancellationToken) in D:\SourceCodes\JZSoft\EasyOC.OrchardCore\OrchardCore\src\OrchardCore\OrchardCore.Recipes.Core\Services\RecipeExecutor.cs:line 103
   --- End of inner exception stack trace ---
   at OrchardCore.Recipes.Services.RecipeExecutor.ExecuteAsync(String executionId, RecipeDescriptor recipeDescriptor, IDictionary`2 environment, CancellationToken cancellationToken) in D:\SourceCodes\JZSoft\EasyOC.OrchardCore\OrchardCore\src\OrchardCore\OrchardCore.Recipes.Core\Services\RecipeExecutor.cs:line 128
   at OrchardCore.Recipes.Services.RecipeExecutor.ExecuteAsync(String executionId, RecipeDescriptor recipeDescriptor, IDictionary`2 environment, CancellationToken cancellationToken) in D:\SourceCodes\JZSoft\EasyOC.OrchardCore\OrchardCore\src\OrchardCore\OrchardCore.Recipes.Core\Services\RecipeExecutor.cs:line 147
   at OrchardCore.Recipes.Services.RecipeExecutor.ExecuteAsync(String executionId, RecipeDescriptor recipeDescriptor, IDictionary`2 environment, CancellationToken cancellationToken) in D:\SourceCodes\JZSoft\EasyOC.OrchardCore\OrchardCore\src\OrchardCore\OrchardCore.Recipes.Core\Services\RecipeExecutor.cs:line 157
   at OrchardCore.Recipes.Services.RecipeMigrator.ExecuteAsync(String recipeFileName, IDataMigration migration) in D:\SourceCodes\JZSoft\EasyOC.OrchardCore\OrchardCore\src\OrchardCore\OrchardCore.Recipes.Core\Services\RecipeMigrator.cs:line 55
   at OrchardCore.Contents.Deployment.ExportContentToDeploymentTarget.ExportContentToDeploymentTargetMigrations.CreateAsync() in D:\SourceCodes\JZSoft\EasyOC.OrchardCore\OrchardCore\src\OrchardCore.Modules\OrchardCore.Contents\Deployment\ExportContentToDeploymentTarget\ExportContentToDeploymentTargetMigrations.cs:line 31
   at OrchardCore.Data.Migration.DataMigrationManager.InvokeMethodAsync(MethodInfo method, IDataMigration migration) in D:\SourceCodes\JZSoft\EasyOC.OrchardCore\OrchardCore\src\OrchardCore\OrchardCore.Data.YesSql\Migration\DataMigrationManager.cs:line 254
   at OrchardCore.Data.Migration.DataMigrationManager.UpdateAsync(String featureId) in D:\SourceCodes\JZSoft\EasyOC.OrchardCore\OrchardCore\src\OrchardCore\OrchardCore.Data.YesSql\Migration\DataMigrationManager.cs:line 216    at OrchardCore.Recipes.Services.RecipeExecutor.ExecuteAsync(String executionId, RecipeDescriptor recipeDescriptor, IDictionary`2 environment, CancellationToken cancellationToken) in D:\SourceCodes\JZSoft\EasyOC.OrchardCore\OrchardCore\src\OrchardCore\OrchardCore.Recipes.Core\Services\RecipeExecutor.cs:line 128
   at OrchardCore.Recipes.Services.RecipeExecutor.ExecuteAsync(String executionId, RecipeDescriptor recipeDescriptor, IDictionary`2 environment, CancellationToken cancellationToken) in D:\SourceCodes\JZSoft\EasyOC.OrchardCore\OrchardCore\src\OrchardCore\OrchardCore.Recipes.Core\Services\RecipeExecutor.cs:line 147
   at OrchardCore.Recipes.Services.RecipeExecutor.ExecuteAsync(String executionId, RecipeDescriptor recipeDescriptor, IDictionary`2 environment, CancellationToken cancellationToken) in D:\SourceCodes\JZSoft\EasyOC.OrchardCore\OrchardCore\src\OrchardCore\OrchardCore.Recipes.Core\Services\RecipeExecutor.cs:line 157
   at OrchardCore.Recipes.Services.RecipeMigrator.ExecuteAsync(String recipeFileName, IDataMigration migration) in D:\SourceCodes\JZSoft\EasyOC.OrchardCore\OrchardCore\src\OrchardCore\OrchardCore.Recipes.Core\Services\RecipeMigrator.cs:line 55
   at OrchardCore.Contents.Deployment.ExportContentToDeploymentTarget.ExportContentToDeploymentTargetMigrations.CreateAsync() in D:\SourceCodes\JZSoft\EasyOC.OrchardCore\OrchardCore\src\OrchardCore.Modules\OrchardCore.Contents\Deployment\ExportContentToDeploymentTarget\ExportContentToDeploymentTargetMigrations.cs:line 31
   at OrchardCore.Data.Migration.DataMigrationManager.InvokeMethodAsync(MethodInfo method, IDataMigration migration) in D:\SourceCodes\JZSoft\EasyOC.OrchardCore\OrchardCore\src\OrchardCore\OrchardCore.Data.YesSql\Migration\DataMigrationManager.cs:line 254
   at OrchardCore.Data.Migration.DataMigrationManager.UpdateAsync(String featureId) in D:\SourceCodes\JZSoft\EasyOC.OrchardCore\OrchardCore\src\OrchardCore\OrchardCore.Data.YesSql\Migration\DataMigrationManager.cs:line 216

```

### PR DESCRIPTION
**Pull request by gvkries**
Since we now have the ability to assign any type to more than one feature, and we also want to avoid having to decorate everything with the `FeatureAttribute`, we need a way to ensure that some features like migrations are only ever assigned to a single feature.
To do this, I've created a new attribute that can be applied to interfaces and classes. This will allow us to decorate only the `IDataMigration` interface, which will avoid having to configure all the other migration classes.

Fixes #16248

### CODE REVIEW

**Review by hyzx86 — APPROVED** [review]
Haven't delved into the code, but after testing it, it's working fine in my project!
Thanks!

File: src/OrchardCore/OrchardCore.Abstractions/Extensions/Features/FeatureTypeDiscoveryAttribute.cs [hunk 1]
```diff
@@ -0,0 +1,38 @@
...
+    /// an <c>InvalidOperationException</c> if the type gets assigned to more than one feature.
+    /// </remarks>
+    public bool SingleFeatureOnly { get; set; }
+
+    public static FeatureTypeDiscoveryAttribute GetFeatureTypeDiscoveryForType(Type type)
+    {
+        return type.GetCustomAttribute<FeatureTypeDiscoveryAttribute>(true)
+            ?? type.GetInterfaces()
+                    .Select(i => i.GetCustomAttribute<FeatureTypeDiscoveryAttribute>(true))
+                    .FirstOrDefault(c => c != null);
```
Comment (hyzx86) [inline src/OrchardCore/OrchardCore.Abstractions/Extensions/Features/FeatureTypeDiscoveryAttribute.cs:36]: Use of relatively well-defined iteration variables
```suggestion
                    .Select(dmType => dmType.GetCustomAttribute<FeatureTypeDiscoveryAttribute>(true))
                    .FirstOrDefault(featureTypeDiscoveryAttr => featureTypeDiscoveryAttr != null);
```

**Comment by MikeAlhayek** [comment]
What if we want to run migration if either feature A or B are enabled? Today, we add the migration to both startups and the migration will be executed once when either or both features are enabled,

File: src/OrchardCore/OrchardCore/Extensions/Features/TypeFeatureProvider.cs [hunk 2]
```diff
@@ -49,7 +49,12 @@ public IEnumerable<Type> GetTypesForFeature(IFeatureInfo feature)
 
         public void TryAdd(Type type, IFeatureInfo feature)
         {
-            _features.AddOrUpdate(type, (key, value) => [value], (key, features, value) => features.Contains(value) ? features : features.Append(value).ToArray(), feature);
+            var features = _features.AddOrUpdate(type, (key, value) => [value], (key, features, value) => features.Contains(value) ? features : features.Append(value).ToArray(), feature);
+
+            if (features.Count() > 1 && (FeatureTypeDiscoveryAttribute.GetFeatureTypeDiscoveryForType(type)?.SingleFeatureOnly ?? false))
+            {
+                throw new InvalidOperationException($"The type {type} can only be assigned to a single feature. Make sure the type is not added to DI by mulitple startup classes.");
```
Comment (sebastienros) [inline src/OrchardCore/OrchardCore/Extensions/Features/TypeFeatureProvider.cs:56]:
```suggestion
                throw new InvalidOperationException($"The type {type} can only be assigned to a single feature. Make sure the type is not added to DI by multiple startup classes.");
```

File: src/OrchardCore/OrchardCore/Shell/Builders/ShellContainerFactory.cs [hunk 3]
```diff
@@ -182,7 +182,10 @@ private void PopulateTypeFeatureProvider(ITypeFeatureProvider typeFeatureProvide
                     {
                         foreach (var type in featureTypes)
```
Comment (sebastienros) [inline src/OrchardCore/OrchardCore/Shell/Builders/ShellContainerFactory.cs:183]:
```suggestion
                        // This is adding the types to the main feature for backward compatibility.
                        // In the future we could stop doing it as we don't expect this to be necessary, and remove the FeatureTypeDiscovery attribute.
                        foreach (var type in featureTypes)
```

File: src/OrchardCore/OrchardCore/Shell/Builders/ShellContainerFactory.cs [hunk 4]
```diff
@@ -182,7 +182,10 @@ private void PopulateTypeFeatureProvider(ITypeFeatureProvider typeFeatureProvide
...
                         {
-                            typeFeatureProvider.TryAdd(type, feature);
+                            if (!SkipExtensionFeatureRegistration(type))
```
Comment (sebastienros) [inline src/OrchardCore/OrchardCore/Shell/Builders/ShellContainerFactory.cs:185]:
```suggestion
                            // If the attribute is present then we explicitly ignore the backward compatibility and skip the registration
                            // in the main feature.
                            if (!SkipExtensionFeatureRegistration(type))
```

**Review by sebastienros — APPROVED** [review]
