### PR TITLE
Fixing pluralization 

### LINKED ISSUE #4617: Error editing text field settings
Unable to edit a text field definition on latest dev. Can repro with the blog recipe by editing the Article content definition.

image

Clicking Edit on a text field results in a System.FormatException:

image

I debugged it and the issue is caused by a localized string in `TextFieldPredefinedSettings.Edit.cshtml` (line 70):

`<span class="hint">@T["A JSON representation of the allowed values, e.g. {0}", "[ { name: 'First option', value: 'option1' }, { name: 'Second option', value: 'option2' } ]"]</span>`

The issue appears to have been introduced by #4559 which added `IHtmlLocalizerFactory` to `NullLocalizerFactory`. If i remove the DI registration of the `IHtmlLocalizerFactory` then it works.

https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore/OrchardCore/Modules/Extensions/ServiceCollectionExtensions.cs#L79

### PR DESCRIPTION
**Pull request by sebastienros**
Fixes #4617

### CODE REVIEW

**Comment by hishamco** [comment]
@sebastienros I will try to simplify the change as much as I can

I dislike `NullLocalizer` to be `public` unless we have too

File: src/OrchardCore/OrchardCore/Localization/NullLocalizerFactory.cs [hunk 1]
```diff
@@ -17,7 +23,7 @@ internal class NullLocalizerFactory : IStringLocalizerFactory, IHtmlLocalizerFac
 
         IHtmlLocalizer IHtmlLocalizerFactory.Create(Type resourceSource) => NullLocalizer.Instance;
 
-        private class NullLocalizer : IStringLocalizer, IHtmlLocalizer
+        public class NullLocalizer : IStringLocalizer, IHtmlLocalizer
```
Comment (hishamco) [inline src/OrchardCore/OrchardCore/Localization/NullLocalizerFactory.cs]: I dislike this change, if the intent to use it in the test, you can use The `IHtmlLocalizer` instance from the DI instead

File: test/OrchardCore.Tests/Localization/NullStringLocalizerTests.cs [hunk 2]
```diff
@@ -41,5 +44,25 @@ public async void LocalizerReturnsFormattedString(string name, string expected,
                 var response = await client.GetAsync("/");
             }
         }
+
+        [Theory]
+        [InlineData("there is one", 1, "there is one", "there are more", new object[0])]
```
Comment (hishamco) [inline test/OrchardCore.Tests/Localization/NullStringLocalizerTests.cs]: I don't think we need `new object[]` for the `arguments`, while its a `params`

File: test/OrchardCore.Tests/Localization/NullStringLocalizerTests.cs [hunk 3]
```diff
@@ -41,5 +44,25 @@ public async void LocalizerReturnsFormattedString(string name, string expected,
...
+        [InlineData("there are more", 2, "there is one", "there are more", new object[0])]
+        [InlineData("there is one (1)", 1, "there is one ({0})", "there are more ({0})", new object[0])]
+        [InlineData("there are more (2)", 2, "there is one ({0})", "there are more ({0})", new object[0])]
+        [InlineData("there is one (1) thing", 1, "there is one ({0}) {1}", "there are more ({0}) {1}", new object[] { "thing" })]
+        [InlineData("there are more (2) thing", 2, "there is one ({0}) {1}", "there are more ({0}) {1}", new object[] { "thing" })]
+        [InlineData("there is one (1) &lt;br/&gt;", 1, "there is one ({0}) {1}", "there are more ({0}) {1}", new object[] { "<br/>" })]
+        [InlineData("there are more (2) &lt;br/&gt;", 2, "there is one ({0}) {1}", "there are more ({0}) {1}", new object[] { "<br/>" })]
+        public void HtmlNullLocalizerSupportsPlural(string expected, int count, string singular, string plural, object[] arguments)
```
Comment (hishamco) [inline test/OrchardCore.Tests/Localization/NullStringLocalizerTests.cs]: `void` -> `Task`

File: src/OrchardCore/OrchardCore/Localization/NullLocalizerFactory.cs [hunk 4]
```diff
@@ -49,10 +57,26 @@ public IEnumerable<LocalizedString> GetAllStrings(bool includeParentCultures)
 
             public IStringLocalizer WithCulture(CultureInfo culture) => Instance;
 
-            LocalizedHtmlString IHtmlLocalizer.this[string name] => new LocalizedHtmlString(name, name);
+            LocalizedHtmlString IHtmlLocalizer.this[string name] => new LocalizedHtmlString(name, name, true);
```
Comment (hishamco) [inline src/OrchardCore/OrchardCore/Localization/NullLocalizerFactory.cs]: Why `isResourcenotFound` is `true`?!!

File: src/OrchardCore/OrchardCore/Localization/NullLocalizerFactory.cs [hunk 5]
```diff
@@ -29,18 +35,20 @@ private class NullLocalizer : IStringLocalizer, IHtmlLocalizer
...
-                        value = String.Format(name, arguments);
+                        translation = pluralArgument.Forms[_defaultPluralRule(pluralArgument.Count)];
+
+                        arguments = new object[pluralArgument.Arguments.Length + 1];
+                        arguments[0] = pluralArgument.Count;
+                        Array.Copy(pluralArgument.Arguments, 0, arguments, 1, pluralArgument.Arguments.Length);
                     }
 
-                    return new LocalizedString(name, value);
+                    translation = String.Format(translation, arguments);
```
Comment (hishamco) [inline src/OrchardCore/OrchardCore/Localization/NullLocalizerFactory.cs]: This always will overwrite the first assignment

**Comment by hishamco** [comment]
@sebastienros hope you like the changes & simplification :)

File: src/OrchardCore/OrchardCore/Localization/NullLocalizerFactory.cs (hunk 4 above)
Comment (sebastienros) [reply src/OrchardCore/OrchardCore/Localization/NullLocalizerFactory.cs]: It's a NullLocalizer, there is no localization, hence I set it to true. But I looked in the code and couldn't find where it would be used for our purpose.

File: src/OrchardCore/OrchardCore/Localization/NullLocalizerFactory.cs (hunk 5 above)
Comment (sebastienros) [reply src/OrchardCore/OrchardCore/Localization/NullLocalizerFactory.cs]: Yes, but look again, the `translation` is what is passed as an argument too.

File: src/OrchardCore/OrchardCore/Localization/NullLocalizerFactory.cs [hunk 6]
```diff
@@ -7,7 +7,13 @@
 
 namespace OrchardCore.Localization
 {
-    internal class NullLocalizerFactory : IStringLocalizerFactory, IHtmlLocalizerFactory
+    /// <remarks>
```
[the remark this answers is not in the document]
Comment (sebastienros) [reply src/OrchardCore/OrchardCore/Localization/NullLocalizerFactory.cs]: Yes, such that next time I read this class I understand why we have two implementations of the localization, as it took me some time to understand.

**Comment by sebastienros** [comment]
Sadly, if you had understood my changes, and the initial issue, you would have realized that this code can't work. But I gave you the benefit of the doubt and tried to run it, and all tests were green ... so I looked again at the code, and became 100% sure that this code should not work, because never is it using the `pluralArgument.Arguments` property, and never is it merging this list with the `Count` as the first, like my changes do.

So I put a breakpoint in the localizer. Never hit. Then I put a breakpoint in the test itself when it calls it, never hit. Then I put a big exception in the code. Not hit. So I changed your tests refactoring to remove the WebHostBuilder, after all you only made the inner class private, so I could still use the factory. 90% of the tests now fail :/ 

So I will revert your changes, which will fix the initial issue. And we should consider looking at other tests that use this web builder pattern.

File: src/OrchardCore/OrchardCore/Localization/NullLocalizerFactory.cs (hunk 4 above)
Comment (hishamco) [reply src/OrchardCore/OrchardCore/Localization/NullLocalizerFactory.cs]: This is useful for logging the missing resources, perhaps it doesn't add value here, but logically it's confusing

**Comment by hishamco** [comment]
Nooo I trust your tests before, but I will not do it again 😊

Let me revise it again and look to the original issue

But again I prefer to separate the null localizers to become `StringNullLocalizer` and `HtmlNullLocalizer` coz the main issue occurs when we add `IHtmlLocalizer`

Having both localizers doesn't make sense to me, but let me check and see what can I come up with

**Comment by hishamco** [comment]
> And we should consider looking at other tests that use this web builder pattern.

This is common on AspNetCore repos, let me double check it again

**Comment by sebastienros** [comment]
I did split the classes as you suggested.

For the tests, put a breakpoint, it won't be hit. Then break the code, the test will be green still.

**Comment by sebastienros** [comment]
Also open a Razor page, and do `T[2, "one item {0} {1}", "more items {0} {1}", "foo"]` then see what it outputs, on dev (before my changes).

I will merge the PR as the issue is bad and blocking, feel free to investigate if you want.

**Comment by hishamco** [comment]
The changes cause another bug, I will try to resolve it while I will look into the `WebHostBuilder` pattern
