### PR TITLE
Fix Json Merge object

### LINKED ISSUE #16588: Merging object does not allow to set a property value to null
### Describe the bug

I created a custom part:

```
public class TestContentPart : ContentPart
{
    public int? Minutes { get; set; }
}
```

Using a driver I have set the `Minutes` value to a number like `10`. Everything works as expected. However, if I want to set it back to `null` after it was set to `10` the value will not allow setting null. because of this setting https://github.com/OrchardCMS/OrchardCore/blob/3fe9612adb08b03114177a485ecc02e52091030c/src/OrchardCore/OrchardCore.Abstractions/Json/JOptions.cs#L23

### Orchard Core version

main

### To Reproduce
Using the following test
```
  [Fact]
  public void Apply_WhenCalledWithNullProperty_SetThePropertyToNull()
  {
      var contentItem = new ContentItem();

      contentItem.Apply(new TestContentPart()
      {
          Minutes = -15,
      });

      var instance = contentItem.As<TestContentPart>();

      Assert.NotNull(instance);
      Assert.Equal(-15, instance.Minutes);

      contentItem.Apply(new TestContentPart()
      {
          Minutes = null,
      });

      var minutes = (int?)contentItem.Content.TestContentPart.Minutes;

      Assert.Null(minutes);
  }
```

### PR DESCRIPTION
**Pull request by MikeAlhayek**
Fix #16588

### CODE REVIEW

File: src/OrchardCore/OrchardCore.Abstractions/Json/Nodes/JObject.cs [hunk 1]
```diff
@@ -98,10 +98,15 @@ public static bool TryParse(string json, out JsonObject? jsonObject, JsonNodeOpt
         {
             if (item.Value is null)
             {
+                if (settings!.MergeNullValueHandling == MergeNullValueHandling.Merge)
+                {
+                    jsonObject[item.Key] = null;
+                }
```
Comment (hishamco) [inline src/OrchardCore/OrchardCore.Abstractions/Json/Nodes/JObject.cs:104]:
```suggestion
                }

```

File: test/OrchardCore.Tests/ContentManagement/ContentElementTests.cs [hunk 2]
```diff
@@ -66,4 +66,35 @@ public void Get_WhenCastingConcreteTypeThenBaseType_ReturnNewInstance()
...
     }
+
+    [Fact]
+    public void Apply_WhenCalledWithNullProperty_SetThePropertyToNull()
+    {
+        var contentItem = new ContentItem();
+
+        contentItem.Apply(new TestContentPart()
+        {
+            Minutes = -15,
```
Comment (hishamco) [inline test/OrchardCore.Tests/ContentManagement/ContentElementTests.cs:77]: It would be better to use `Theory` to pass the inputs and reduce the duplicate call

**Review by hishamco — CHANGES_REQUESTED** [review]

File: test/OrchardCore.Tests/ContentManagement/ContentElementTests.cs (hunk 2 above)
Comment (MikeAlhayek) [reply test/OrchardCore.Tests/ContentManagement/ContentElementTests.cs:77]: there is a single parameter here. Why would we change this to `Theory`

Comment (hishamco) [reply test/OrchardCore.Tests/ContentManagement/ContentElementTests.cs:77]: I will modify the unit test if you don't mind

Comment (MikeAlhayek) [reply test/OrchardCore.Tests/ContentManagement/ContentElementTests.cs:77]: okay

**Review by hishamco — APPROVED** [review]

File: test/OrchardCore.Tests/ContentManagement/ContentElementTests.cs [hunk 3]
```diff
@@ -66,4 +66,30 @@ public void Get_WhenCastingConcreteTypeThenBaseType_ReturnNewInstance()
...
+        // Act
+        contentItem.Apply(new TestContentPart()
+        {
+            Minutes = minutes,
+        });
+
+        var part = contentItem.As<TestContentPart>();
+
+        // Assert
+        Assert.Equal(minutes, part.Minutes);
```
Comment (MikeAlhayek) [inline test/OrchardCore.Tests/ContentManagement/ContentElementTests.cs:88]: @hishamco this test is now useless. I think you missed understanding the test that I put together. Your version of the test will pass even if you apply it to the main branch. The test I had before your commit tests to see if the object was updated from a value back to null. So please revert the last commit

Comment (hishamco) [reply test/OrchardCore.Tests/ContentManagement/ContentElementTests.cs:88]: Wait a minute let me double check again

Comment (hishamco) [reply test/OrchardCore.Tests/ContentManagement/ContentElementTests.cs:88]: I just understand what you mean, seems no need for the `Theory` here, so I will revert the test changes
