### PR TITLE
Widgets overwrite zone tag helper - log warning when the Zone isn't a Shape. (Lombiq Technologies: OCORE-90)

### LINKED ISSUE #11481: Widgets overwrite zone tag helper.
### Describe the bug
I can't use both `<zone>` tag helpers and widgets for the same zone. If you have a widget in the zone, the content in zone tag helpers are ignored.

### To Reproduce
1. Create a new Orchard Core CMS Web App solution.
2. Add a new Orchard Core Theme project
2. Replace the _Views/Layout.liquid_ with _Views/Layout.cshtml_ having the following content to keep it simple:
```razor
@inherits OrchardCore.DisplayManagement.Razor.RazorPage<TModel>

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, OrchardCore.DisplayManagement
@addTagHelper *, OrchardCore.ResourceManagement

<zone name="Footer">
<p>Hello from zone tag helper!</p>
</zone>

@await RenderSectionAsync("Content", required: false)
@await RenderSectionAsync("Footer", required: false)
```
3. Launch and set up the webapp.
4. Go to /Admin/Themes, and select the newly created theme.
5. Confirm "Hello from zone tag helper!" is visible on the home page.
6. Create a zone "Footer" and a layer "Always" (boolean true condition).
8. Create a widget content type with Html Body and add a new item with "Hello from Widget!" to the Footer zone.
9. Go back to the home page. You only see `Hello from Widget!` and any tag helpers are ignored.

### Expected behavior
You should see
```
Hello from zone tag helper!
Hello from Widget!
```
in the footer.

### PR DESCRIPTION
**Pull request by DAud-IcI**
Fixes #11481

Add warning logging when ZoneTagHelper can't be applied.

### CODE REVIEW

File: src/OrchardCore/OrchardCore.DisplayManagement/TagHelpers/ZoneTagHelper.cs [hunk 1]
```diff
@@ -41,6 +44,14 @@ public async override Task ProcessAsync(TagHelperContext context, TagHelperOutpu
             {
                 await shape.AddAsync(childContent, Position);
             }
+            else
+            {
+                _logger.LogWarning(
+                    "Unable to add shape to the zone using the <zone2> tag helper because the zone's type is " +
```
Comment (Skrypt) [inline src/OrchardCore/OrchardCore.DisplayManagement/TagHelpers/ZoneTagHelper.cs:50]: `<zone>` instead of `<zone2>`

Comment (ns8482e) [reply src/OrchardCore/OrchardCore.DisplayManagement/TagHelpers/ZoneTagHelper.cs]: @jtkech should we take a step further and actually allow shapes in position wrapper for rendering?

File: src/OrchardCore/OrchardCore.DisplayManagement/TagHelpers/ZoneTagHelper.cs [hunk 2]
```diff
@@ -41,6 +44,14 @@ public async override Task ProcessAsync(TagHelperContext context, TagHelperOutpu
             {
                 await shape.AddAsync(childContent, Position);
             }
+            else
+            {
+                _logger.LogWarning(
+                    "Unable to add shape to the zone using the <zone> tag helper because the zone's type is " +
+                    "\"{ActualType}\" instead of the expected {ExpectedType}",
+                    zone.GetType().FullName,
+                    nameof(Shape));
```
Comment (hishamco) [inline src/OrchardCore/OrchardCore.DisplayManagement/TagHelpers/ZoneTagHelper.cs:53]: How the `{ExpectedType}` will be different while the `nameof(Shape)` returns "Shape" all the time?!!

**Review by hishamco — CHANGES_REQUESTED** [review]

File: src/OrchardCore/OrchardCore.DisplayManagement/TagHelpers/ZoneTagHelper.cs (hunk 2 above)
[the remark this answers is not in the document]
Comment (DAud-IcI) [reply src/OrchardCore/OrchardCore.DisplayManagement/TagHelpers/ZoneTagHelper.cs:53]: `{ExpectedType}` is always supposed to be `"Shape"`. I only made it a parameter because I think it's clearer this way. Do you want me to remove the parameter and just type "Shape" in the message string instead?

[the remark this answers is not in the document]
Comment (hishamco) [reply src/OrchardCore/OrchardCore.DisplayManagement/TagHelpers/ZoneTagHelper.cs:53]: > {ExpectedType} is always supposed to be "Shape"

No need to remove it, it's fine to keep it this way

Comment (DAud-IcI) [reply src/OrchardCore/OrchardCore.DisplayManagement/TagHelpers/ZoneTagHelper.cs:53]: Not everyone knows about the pre-rendering and if you are developing a theme then it can have logical uses. (In my case I had a shape in the base theme's layout's header that the derived theme can override to inject stuff). 
I didn't know about PositionWrapper earlier and I thought that something else broke. The purpose of this PR is to be more developer friendly by warning about the irregular behavior.

**Review by hishamco — APPROVED** [review]

**Review by sebastienros — APPROVED** [review]
